version: "3"

env:
  UV_CACHE_DIR: "{{.TASKFILE_DIR}}/tmp/uv-cache"
  PLAYWRIGHT_BROWSERS_PATH: "{{.TASKFILE_DIR}}/tmp/playwright-browsers"

includes:
  core:
    taskfile: ./taskfile/core.yml
    dir: .
    flatten: true
  taqt:
    taskfile: ./taskfile/taqt.yml
    dir: .
