import type { FC } from "hono/jsx";
import type { JSX } from "hono/jsx/jsx-runtime";
import { BRAND_NAME } from "../brand";

const HTMX_SCRIPT = "https://cdn.jsdelivr.net/npm/htmx.org@2.0.4/dist/htmx.min.js";
export const HTMX_CONFLICT_SWAP_SCRIPT = [
  "document.body.addEventListener('htmx:beforeSwap', function (event) {",
  "  if (event.detail.xhr.status !== 409) return;",
  "  event.detail.shouldSwap = true;",
  "  event.detail.isError = false;",
  "});",
].join("\n");
export const POPOVER_DISMISS_SCRIPT = [
  "document.addEventListener('click', function (event) {",
  "  var target = event.target;",
  "  var cancel = target && target.closest ? target.closest('[data-popover-cancel]') : null;",
  "  Array.prototype.forEach.call(document.querySelectorAll('[data-popover-close][open]'), function (details) {",
  "    if (cancel ? details.contains(cancel) : !details.contains(target)) details.removeAttribute('open');",
  "  });",
  "  var panel = document.querySelector('[data-popover-close-href]');",
  "  if (!panel || panel.contains(event.target)) return;",
  "  var href = panel.getAttribute('data-popover-close-href');",
  "  if (href) window.location.assign(href);",
  "});",
  "document.addEventListener('change', function (event) {",
  "  var target = event.target;",
  "  var details = target && target.closest ? target.closest('[data-popover-close]') : null;",
  "  if (details) details.removeAttribute('open');",
  "});",
].join("\n");
export const TASK_FORM_SHORTCUT_SCRIPT = [
  'document.addEventListener("keydown", function (event) {',
  '  if (!event.ctrlKey || event.key !== "Enter") return;',
  "  var target = event.target;",
  '  var editor = target && target.closest ? target.closest("[data-description-editor]") : null;',
  '  var isDescriptionEditor = Boolean(editor);',
  '  if (!target || (!isDescriptionEditor && target.name !== "title" && target.name !== "description")) return;',
  '  var form = target.closest ? target.closest("form[data-task-form]") : null;',
  "  if (!form) return;",
  "  event.preventDefault();",
  '  if (form.dataset.shortcutSubmitting === "true") return;',
  "  if (!form.checkValidity()) { form.reportValidity(); return; }",
  '  form.dataset.shortcutSubmitting = "true";',
  "  form.requestSubmit();",
  "});",
  'window.addEventListener("pageshow", function (event) {',
  "  if (!event.persisted) return;",
  "  if (!document.querySelector('form[data-task-form=\"edit\"]')) return;",
  "  window.location.reload();",
  "});",
].join("\n");
export const DESCRIPTION_EDITOR_SCRIPT = [
  "function descriptionEditorValue(editor) {",
  '  return editor.innerText.replace(/\\n$/, "");',
  "}",
  "function syncDescriptionEditor(editor) {",
  '  var form = editor.closest("form");',
  '  var hidden = form ? form.querySelector("textarea[data-description-value]") : null;',
  '  if (hidden) hidden.value = descriptionEditorValue(editor);',
  "}",
  "function linkifyDescriptionEditor(editor) {",
  '  var walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);',
  "  var nodes = [];",
  "  while (walker.nextNode()) nodes.push(walker.currentNode);",
  "  nodes.forEach(function (node) {",
  '    if (!node.parentElement || node.parentElement.closest("a")) return;',
  "    var text = node.nodeValue || \"\";",
  '    var pattern = /https?:\\/\\/[^\\s<>]+/g;',
  "    var match;",
  "    var cursor = 0;",
  "    var fragment = document.createDocumentFragment();",
  "    var changed = false;",
  "    while ((match = pattern.exec(text)) !== null) {",
  "      var raw = match[0];",
  '      var url = raw.replace(/[.,!?;:]+$/, "");',
  "      if (!url) continue;",
  "      if (match.index > cursor) fragment.appendChild(document.createTextNode(text.slice(cursor, match.index)));",
  "      var link = document.createElement(\"a\");",
  "      link.href = url;",
  "      link.textContent = url;",
  "      fragment.appendChild(link);",
  "      if (raw.length > url.length) fragment.appendChild(document.createTextNode(raw.slice(url.length)));",
  "      cursor = match.index + raw.length;",
  "      changed = true;",
  "    }",
  "    if (!changed) return;",
  "    if (cursor < text.length) fragment.appendChild(document.createTextNode(text.slice(cursor)));",
  "    node.parentNode.replaceChild(fragment, node);",
  "  });",
  "}",
  "function initializeDescriptionEditors() {",
  '  document.querySelectorAll("[data-description-editor]").forEach(function (editor) {',
  '    if (editor.dataset.descriptionEditorInitialized === "true") { syncDescriptionEditor(editor); return; }',
  '    editor.dataset.descriptionEditorInitialized = "true";',
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  '    editor.addEventListener("input", function () { syncDescriptionEditor(editor); });',
  '    editor.addEventListener("click", function (event) {',
  '      var link = event.target && event.target.closest ? event.target.closest("a") : null;',
  '      if (!link || !editor.contains(link)) return;',
  "      event.preventDefault();",
  "      if (event.ctrlKey || event.metaKey) {",
  '        window.open(link.href, "_blank", "noopener,noreferrer");',
  "      } else {",
  "        window.location.assign(link.href);",
  "      }",
  "    });",
  '    editor.addEventListener("paste", function (event) {',
  '      var text = event.clipboardData ? event.clipboardData.getData("text/plain") : "";',
  "      if (!text) return;",
  "      event.preventDefault();",
  '      document.execCommand("insertText", false, text);',
  "      linkifyDescriptionEditor(editor);",
  "      syncDescriptionEditor(editor);",
  "    });",
  "  });",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeDescriptionEditors);',
  'document.addEventListener("htmx:load", initializeDescriptionEditors);',
  "function taskFormDraftKey(form) {",
  '  if (form.getAttribute("data-task-form") === "new") return null;',
  '  var action = form.getAttribute("action") || "";',
  '  var match = action.match(/\\/tasks\\/([^/?#]+)/);',
  '  if (match) return "siftq.task-draft:" + decodeURIComponent(match[1]);',
  "  return null;",
  "}",
  "function removeTaskDraft(taskId) {",
  '  if (!taskId) return;',
  '  try { localStorage.removeItem("siftq.task-draft:" + taskId); } catch (e) {}',
  "}",
  "function taskFormDraftVersion(form) {",
  '  var versionInput = form.querySelector("#task-version");',
  "  if (!versionInput) return null;",
  "  var version = Number(versionInput.value);",
  '  return Number.isFinite(version) ? version : null;',
  "}",
  "function saveTaskFormDraft(form) {",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  '  var titleInput = form.querySelector(\'input[name="title"]\');',
  '  var hidden = form.querySelector("textarea[data-description-value]");',
  '  var editor = form.querySelector("[data-description-editor]");',
  "  var title = titleInput ? titleInput.value : \"\";",
  "  var description = hidden ? hidden.value : editor ? descriptionEditorValue(editor) : \"\";",
  "  var draft = { title: title, description: description, updatedAt: Date.now() };",
  "  var version = taskFormDraftVersion(form);",
  "  if (version !== null) draft.version = version;",
  "  try {",
  "    localStorage.setItem(key, JSON.stringify(draft));",
  "  } catch (e) {}",
  "}",
  "function scheduleTaskFormDraft(form) {",
  "  if (form._taskDraftTimer) clearTimeout(form._taskDraftTimer);",
  "  form._taskDraftTimer = setTimeout(function () { saveTaskFormDraft(form); }, 500);",
  "}",
  "function restoreTaskFormDraft(form) {",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  var raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  var draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  '  if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  "  if (typeof draft.updatedAt === 'number' && Date.now() - draft.updatedAt >= 24 * 60 * 60 * 1000) {",
  "    try { localStorage.removeItem(key); } catch (e) {}",
  "    return;",
  "  }",
  "  if (typeof draft.version === 'number') {",
  "    var serverVersion = taskFormDraftVersion(form);",
  "    if (serverVersion !== null && serverVersion !== draft.version) {",
  "      try { localStorage.removeItem(key); } catch (e) {}",
  "      return;",
  "    }",
  "  }",
  '  var titleInput = form.querySelector(\'input[name="title"]\');',
  "  if (titleInput) titleInput.value = draft.title;",
  '  var editor = form.querySelector("[data-description-editor]");',
  "  if (editor) {",
  "    editor.textContent = draft.description;",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "  } else {",
  '    var hidden = form.querySelector("textarea[data-description-value]");',
  "    if (hidden) hidden.value = draft.description;",
  "  }",
  "}",
  "function initializeTaskFormDrafts() {",
  '  document.querySelectorAll("form[data-task-form]").forEach(function (form) {',
  '    if (form.dataset.taskDraftInitialized === "true") return;',
  '    form.dataset.taskDraftInitialized = "true";',
  "    restoreTaskFormDraft(form);",
  '    form.addEventListener("input", function () { scheduleTaskFormDraft(form); });',
  "  });",
  "}",
  "function refreshTaskFormDraftVersion() {",
  '  var form = document.querySelector(\'form[data-task-form="edit"]\');',
  "  if (!form) return;",
  "  var version = taskFormDraftVersion(form);",
  "  if (version === null) return;",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  var raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  var draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  '  if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  "  if (draft.version === version) return;",
  "  draft.version = version;",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (e) {}",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeTaskFormDrafts);',
  'document.addEventListener("htmx:load", initializeTaskFormDrafts);',
  'document.body.addEventListener("htmx:oobAfterSwap", refreshTaskFormDraftVersion);',
  'document.body.addEventListener("htmx:afterSettle", refreshTaskFormDraftVersion);',
  'document.body.addEventListener("htmx:afterRequest", function (event) {',
  '  var detail = event.detail || {};',
  '  var xhr = detail.xhr;',
  '  var status = xhr ? xhr.status : 0;',
  '  if (status < 200 || status >= 300) return;',
  '  try { if (xhr && typeof xhr.getResponseHeader === "function" && !xhr.getResponseHeader("HX-Redirect")) return; } catch (e) { return; }',
  '  var elt = detail.elt;',
  '  var form = elt && elt.closest ? elt.closest("form[data-task-form]") : null;',
  '  if (!form) return;',
  '  if (form._taskDraftTimer) { clearTimeout(form._taskDraftTimer); form._taskDraftTimer = null; }',
  '  var key = taskFormDraftKey(form);',
  '  if (!key) return;',
  '  try { localStorage.removeItem(key); } catch (e) {}',
  '});',
  'document.addEventListener("submit", function (event) {',
  '  var form = event.target;',
  '  if (!form || !form.matches || !form.matches(\'form[action="/logout"]\')) return;',
  "  try {",
  "    var remove = [];",
  "    for (var i = 0; i < localStorage.length; i += 1) {",
  "      var key = localStorage.key(i);",
  '      if (key && key.indexOf("siftq.task-draft:") === 0) remove.push(key);',
  "    }",
  "    remove.forEach(function (key) { localStorage.removeItem(key); });",
  "  } catch (e) {}",
  "});",
].join("\n");
export const TASK_LIST_SELECTION_SCRIPT = [
  "function initializeTaskListSelection() {",
  '  var list = document.querySelector("[data-task-list]");',
  '  if (!list || list.dataset.selectionInitialized === "true") return;',
  '  list.dataset.selectionInitialized = "true";',
  '  var selectAll = list.querySelector("[data-task-select-all]");',
  '  var statusTabs = list.querySelector("[data-task-status-tabs]");',
  '  var selectionSummary = list.querySelector("[data-task-selection-summary]");',
  '  var actionButtons = list.querySelectorAll("[data-task-action]");',
  '  var feedback = list.querySelector("[data-task-selection-feedback]");',
  "  var actionPending = false;",
  '  var selects = function () { return Array.prototype.slice.call(list.querySelectorAll("[data-task-select]")); };',
  "  function selectedInputs() {",
  '    return selects().filter(function (checkbox) { return checkbox.checked; }).map(function (checkbox) {',
  '      var row = checkbox.closest("[data-task-row]");',
  '      var id = row && row.getAttribute("data-task-id");',
  '      var version = row && row.getAttribute("data-version");',
  '      if (!id || !version) return null;',
  '      return { id: id, version: Number(version) };',
  '    }).filter(function (input) { return input !== null; });',
  "  }",
  "  function showFeedback(message) {",
  '    if (!feedback) return;',
  '    feedback.hidden = false;',
  '    feedback.classList.add("error");',
  '    feedback.textContent = message;',
  "  }",
  "  function setPending(pending) {",
  "    actionPending = pending;",
  '    actionButtons.forEach(function (button) { button.disabled = pending || selectedInputs().length === 0; });',
  '    if (selectAll) selectAll.disabled = pending || selects().length === 0;',
  "  }",
  "  function syncSelection() {",
  "    var checkboxes = selects();",
  '    var selected = checkboxes.filter(function (checkbox) { return checkbox.checked; });',
  '    if (selectAll) { selectAll.checked = checkboxes.length > 0 && selected.length === checkboxes.length; selectAll.indeterminate = selected.length > 0 && selected.length < checkboxes.length; selectAll.disabled = actionPending || checkboxes.length === 0; }',
  '    if (statusTabs) statusTabs.hidden = selected.length > 0;',
  '    if (selectionSummary) { selectionSummary.hidden = selected.length === 0; selectionSummary.textContent = selected.length + " of " + checkboxes.length + " selected"; }',
  '    actionButtons.forEach(function (button) { button.disabled = actionPending || selected.length === 0; });',
  '    list.querySelectorAll("[data-task-row]").forEach(function (row) {',
  '      var checkbox = row.querySelector("[data-task-select]");',
  '      if (checkbox) row.classList.toggle("is-selected", checkbox.checked);',
  "    });",
  "  }",
  '  if (selectAll) selectAll.addEventListener("change", function () { selects().forEach(function (checkbox) { checkbox.checked = selectAll.checked; }); syncSelection(); });',
  '  list.addEventListener("change", function (event) { if (event.target.matches("[data-task-select]")) syncSelection(); });',
  "  function submitBulkAction(action, inputs) {",
  "    setPending(true);",
  '    var isDelete = action === "delete";',
  '    var request = fetch(isDelete ? "/api/tasks/bulk" : "/api/tasks/bulk/status", {',
  '      method: isDelete ? "DELETE" : "PATCH",',
  '      headers: { "Content-Type": "application/json" },',
  '      body: JSON.stringify(isDelete ? { tasks: inputs } : { status: action, tasks: inputs }),',
  "    });",
  '    request.then(function (response) {',
  '      if (!response.ok) { showFeedback(response.status === 409 ? "Task was updated elsewhere. Reload the list." : "Bulk action failed."); return false; }',
  '      return true;',
  '    }).then(function (succeeded) { if (succeeded) { if (isDelete && typeof removeTaskDraft === "function") inputs.forEach(function (input) { removeTaskDraft(input.id); }); window.location.reload(); } }).catch(function () { showFeedback("Bulk action failed."); }).finally(function () { setPending(false); });',
  "  }",
  "  function renderDeleteDialog(inputs) {",
  '    var backdrop = document.createElement("div");',
  '    backdrop.className = "matrix-modal-backdrop";',
  '    var dialog = document.createElement("div");',
  '    dialog.className = "matrix-modal";',
  '    var message = document.createElement("p");',
  '    message.className = "matrix-modal-text";',
  '    message.textContent = "選択した" + inputs.length + "件のタスクを削除しますか？";',
  '    dialog.appendChild(message);',
  '    var row = document.createElement("div");',
  '    row.className = "matrix-modal-actions";',
  '    ["キャンセル", "削除"].forEach(function (label, index) {',
  '      var button = document.createElement("button");',
  '      button.type = "button";',
  '      button.className = "matrix-modal-button " + (index === 1 ? "matrix-modal-button--danger" : "matrix-modal-button--cancel");',
  '      button.textContent = label;',
  '      button.setAttribute("data-task-list-delete", index === 1 ? "confirm" : "cancel");',
  '      row.appendChild(button);',
  '    });',
  '    dialog.appendChild(row);',
  '    backdrop.addEventListener("click", function (event) {',
  '      var button = event.target.closest ? event.target.closest("[data-task-list-delete]") : null;',
  '      if (!button) return;',
  '      backdrop.remove();',
  '      if (button.getAttribute("data-task-list-delete") === "confirm") submitBulkAction("delete", inputs);',
  '    });',
  '    backdrop.appendChild(dialog);',
  '    document.body.appendChild(backdrop);',
  "  }",
  '  list.addEventListener("click", function (event) {',
  '    var action = event.target.closest ? event.target.closest("[data-task-action]") : null;',
  '    if (!action) return;',
  '    var inputs = selectedInputs();',
  '    if (actionPending || inputs.length === 0) return;',
  '    event.preventDefault();',
  '    var actionName = action.getAttribute("data-task-action");',
  '    var menu = action.closest(".task-bulk-menu");',
  '    if (menu) menu.removeAttribute("open");',
  '    if (actionName === "delete") { renderDeleteDialog(inputs); return; }',
  '    if (actionName === "do" || actionName === "done" || actionName === "skip") submitBulkAction(actionName, inputs);',
  "  });",
  "  syncSelection();",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeTaskListSelection);',
  'document.addEventListener("htmx:load", initializeTaskListSelection);',
].join("\n");
export const MATRIX_DND_SCRIPT = [
  "var matrixDraggingCard = null;",
  "var matrixDragPointerId = null;",
  "var matrixDragStart = null;",
  "var matrixDropTarget = null;",
  "var matrixDndPending = false;",
  "var suppressMatrixCardClick = false;",
  "var matrixAutoScrollFrame = null;",
  "var matrixAutoScrollList = null;",
  "var matrixAutoScrollDelta = 0;",
  "var matrixDragGhost = null;",
  "var matrixDragPlaceholder = null;",
  "var matrixDragGrabOffset = null;",
  "var MATRIX_DRAG_THRESHOLD = 5;",
  "function showDndConflict() {",
  '  var notice = document.getElementById("dnd-conflict");',
  "  if (notice) notice.hidden = false;",
  "}",
  "function restoreMatrix() {",
  '  fetch("/", { headers: { "HX-Request": "true" } })',
  "    .then(function (response) { return response.text(); })",
  "    .then(function (html) {",
  '      var page = document.getElementById("page");',
  "      if (page) page.innerHTML = html;",
  "      showDndConflict();",
  "      initMatrixDnd();",
  "    });",
  "}",
  "function matrixCards(list) {",
  '  return Array.prototype.slice.call(list.querySelectorAll(":scope > .task-card"));',
  "}",
  "function matrixDropIndex(list, pointerY) {",
  "  var cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  for (var index = 0; index < cards.length; index += 1) {",
  "    var box = cards[index].getBoundingClientRect();",
  "    if (pointerY < box.top + box.height / 2) return index;",
  "  }",
  "  return cards.length;",
  "}",
  "function matrixDropListFromPoint(x, y) {",
  "  var element = document.elementFromPoint(x, y);",
  '  var quadrant = element && element.closest ? element.closest(".area--quadrant[data-drop-area]") : null;',
  '  return quadrant ? quadrant.querySelector(".matrix-cards[data-dnd-group]") : null;',
  "}",
  "function setMatrixDropTarget(target) {",
  "  if (matrixDropTarget === target) return;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.remove("drop-target");',
  "  matrixDropTarget = target;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.add("drop-target");',
  "}",
  "function stopMatrixAutoScroll() {",
  "  if (matrixAutoScrollFrame !== null) {",
  "    window.cancelAnimationFrame(matrixAutoScrollFrame);",
  "    matrixAutoScrollFrame = null;",
  "  }",
  "  matrixAutoScrollList = null;",
  "  matrixAutoScrollDelta = 0;",
  "}",
  "function stepMatrixAutoScroll() {",
  "  matrixAutoScrollFrame = null;",
  "  if (!matrixAutoScrollList || matrixAutoScrollDelta === 0) return;",
  "  matrixAutoScrollList.scrollTop += matrixAutoScrollDelta * 14;",
  "  matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function updateMatrixAutoScroll(pointerY, list) {",
  "  if (!list || list.scrollHeight <= list.clientHeight) { stopMatrixAutoScroll(); return; }",
  "  var box = list.getBoundingClientRect();",
  "  var edge = 32;",
  "  var delta = pointerY < box.top + edge ? -1 : pointerY > box.bottom - edge ? 1 : 0;",
  "  if (delta === 0) { stopMatrixAutoScroll(); return; }",
  "  matrixAutoScrollList = list;",
  "  matrixAutoScrollDelta = delta;",
  "  if (matrixAutoScrollFrame === null) matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function clearMatrixDnd() {",
  '  if (matrixDraggingCard) matrixDraggingCard.classList.remove("dragging");',
  "  if (matrixDragGhost) { matrixDragGhost.remove(); matrixDragGhost = null; }",
  "  if (matrixDragPlaceholder) { matrixDragPlaceholder.remove(); matrixDragPlaceholder = null; }",
  "  matrixDragGrabOffset = null;",
  "  setMatrixDropTarget(null);",
  "  stopMatrixAutoScroll();",
  "  matrixDraggingCard = null;",
  "  matrixDragPointerId = null;",
  "  matrixDragStart = null;",
  "}",
  "function setMatrixDndPending(pending) {",
  "  matrixDndPending = pending;",
  "}",
  "function matrixCardFromEvent(event) {",
  "  var element = event.target;",
  '  return element && element.closest ? element.closest(".matrix-cards .task-card") : null;',
  "}",
  "function positionMatrixGhost(x, y) {",
  "  if (!matrixDragGhost || !matrixDragGrabOffset) return;",
  "  matrixDragGhost.style.left = (x - matrixDragGrabOffset.x) + 'px';",
  "  matrixDragGhost.style.top = (y - matrixDragGrabOffset.y) + 'px';",
  "}",
  "function positionMatrixPlaceholder(list, pointerY) {",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  if (!list || !matrixDragPlaceholder) return;",
  "  var cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  var index = matrixDropIndex(list, pointerY);",
  "  list.insertBefore(matrixDragPlaceholder, cards[index] || null);",
  "}",
  "function updateMatrixDrag(event) {",
  "  positionMatrixGhost(event.clientX, event.clientY);",
  "  var target = matrixDropListFromPoint(event.clientX, event.clientY);",
  "  setMatrixDropTarget(target);",
  "  positionMatrixPlaceholder(target, event.clientY);",
  "  updateMatrixAutoScroll(event.clientY, target);",
  "}",
  "function startMatrixDrag(event) {",
  '  matrixDraggingCard.classList.add("dragging");',
  "  suppressMatrixCardClick = true;",
  "  try { matrixDraggingCard.setPointerCapture(matrixDragPointerId); } catch (error) {}",
  "  var rect = matrixDraggingCard.getBoundingClientRect();",
  "  matrixDragGrabOffset = { x: event.clientX - rect.left, y: event.clientY - rect.top };",
  '  var ghost = matrixDraggingCard.cloneNode(true);',
  '  ghost.classList.remove("dragging");',
  '  ghost.classList.add("matrix-drag-ghost");',
  '  ghost.style.width = rect.width + "px";',
  "  document.body.appendChild(ghost);",
  "  matrixDragGhost = ghost;",
  '  var placeholder = document.createElement("div");',
  '  placeholder.className = "drop-line matrix-drag-placeholder";',
  '  placeholder.style.height = rect.height + "px";',
  "  matrixDragPlaceholder = placeholder;",
  "  updateMatrixDrag(event);",
  "}",
  "function finishMatrixDrag(event) {",
  "  var card = matrixDraggingCard;",
  "  var target = matrixDropTarget;",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  var index = target ? matrixDropIndex(target, event.clientY) : 0;",
  "  clearMatrixDnd();",
  "  setTimeout(function () { suppressMatrixCardClick = false; }, 0);",
  "  if (!target) return;",
  "  var cards = matrixCards(target).filter(function (candidate) { return candidate !== card; });",
  "  var reference = cards[index] || null;",
  "  target.insertBefore(card, reference);",
  "  persistMatrixDrop(card, target);",
  "}",
  "function initMatrixDnd() {",
  "  clearMatrixDnd();",
  "}",
  "function persistMatrixDrop(card, target) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  '  var area = target.getAttribute("data-area");',
  "  var order = matrixCards(target).indexOf(card);",
  "  if (!taskId || !version || area === null || order < 0) return;",
  "  setMatrixDndPending(true);",
  '  return fetch("/api/tasks/reorder", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ id: taskId, area: Number(area), order: order, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) { showDndConflict(); restoreMatrix(); return null; }",
  "    return response.json();",
  "  }).then(function (tasks) {",
  "    if (!Array.isArray(tasks)) return;",
  "    tasks.forEach(function (task) {",
  '      if (!task || typeof task.id !== "string" || typeof task.version !== "number") return;',
  '      document.querySelectorAll(".task-card[data-task-id]").forEach(function (updatedCard) {',
  '        if (updatedCard.getAttribute("data-task-id") === task.id) {',
  '          updatedCard.setAttribute("data-version", String(task.version));',
  "        }",
  "      });",
  "    });",
  "  }).finally(function () { setMatrixDndPending(false); });",
  "}",
  'document.addEventListener("pointerdown", function (event) {',
  "  if (event.button !== 0 || !event.isPrimary || matrixDndPending || matrixDraggingCard) return;",
  "  var card = matrixCardFromEvent(event);",
  '  if (!card || !card.getAttribute("data-task-id")) return;',
  "  matrixDraggingCard = card;",
  "  matrixDragPointerId = event.pointerId;",
  "  matrixDragStart = { x: event.clientX, y: event.clientY };",
  "});",
  'document.addEventListener("pointermove", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  '  if (!matrixDraggingCard.classList.contains("dragging")) {',
  "    var dx = event.clientX - matrixDragStart.x;",
  "    var dy = event.clientY - matrixDragStart.y;",
  "    if (Math.abs(dx) < MATRIX_DRAG_THRESHOLD && Math.abs(dy) < MATRIX_DRAG_THRESHOLD) return;",
  "    startMatrixDrag(event);",
  "    return;",
  "  }",
  "  event.preventDefault();",
  "  updateMatrixDrag(event);",
  "});",
  'document.addEventListener("pointerup", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  '  if (matrixDraggingCard.classList.contains("dragging")) { finishMatrixDrag(event); return; }',
  "  clearMatrixDnd();",
  "});",
  'document.addEventListener("pointercancel", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  "  clearMatrixDnd();",
  "});",
  'document.addEventListener("click", function (event) {',
  "  if (!suppressMatrixCardClick) return;",
  "  var card = matrixCardFromEvent(event);",
  "  if (!card) return;",
  "  event.preventDefault();",
  "  event.stopPropagation();",
  "  suppressMatrixCardClick = false;",
  "}, true);",
  'document.addEventListener("click", function (event) {',
  "  if (event.defaultPrevented) return;",
  '  if (event.target.closest("a, button, input, select, textarea")) return;',
  '  var quadrant = event.target.closest(".area--quadrant[data-drop-area]");',
  "  if (!quadrant) return;",
  '  var area = quadrant.getAttribute("data-drop-area");',
  "  if (area === null) return;",
  '  window.location.assign("/tasks/new?area=" + encodeURIComponent(area) + "&from=matrix");',
  "});",
  'document.addEventListener("DOMContentLoaded", initMatrixDnd);',
  'document.addEventListener("htmx:load", initMatrixDnd);',
  "var matrixMenu = null;",
  "var matrixMenuCard = null;",
  "var matrixActionPending = false;",
  "var matrixMenuJustOpened = false;",
  "function closeMatrixMenu() {",
  '  if (!matrixMenu) return;',
  "  matrixMenu.remove();",
  "  matrixMenu = null;",
  "  matrixMenuCard = null;",
  "  matrixMenuJustOpened = false;",
  "}",
  "function removeMatrixCard(card) {",
  "  if (card) card.remove();",
  "  matrixMenuCard = null;",
  "}",
  "function setMatrixActionPending(pending) {",
  "  matrixActionPending = pending;",
  "  setMatrixDndPending(pending);",
  "}",
  "function restoreMatrixAfterAction() {",
  "  showDndConflict();",
  "  return restoreMatrix();",
  "}",
  "function persistMatrixStatus(card, status) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "PATCH",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ status: status, version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) removeMatrixCard(card);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function setMatrixCardWorking(card, working, version) {",
  '  if (typeof version === "number") card.setAttribute("data-version", String(version));',
  '  var header = card.querySelector(".task-card-header");',
  '  var badge = card.querySelector(".working-badge");',
  "  if (working) {",
  '    card.classList.add("task-card--working");',
  "    if (!badge && header) {",
  '      badge = document.createElement("span");',
  '      badge.className = "working-badge";',
  '      badge.textContent = "working";',
  "      header.appendChild(badge);",
  "    }",
  "  } else {",
  '    card.classList.remove("task-card--working");',
  "    if (badge) badge.remove();",
  "  }",
  "}",
  "function persistMatrixWorking(card, working) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "PATCH",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ working: working, version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) setMatrixCardWorking(card, task.working === true, task.version);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function persistMatrixDelete(card) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "DELETE",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction();",
  '    if (typeof removeTaskDraft === "function") removeTaskDraft(taskId);',
  "    removeMatrixCard(card);",
  "    return null;",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function renderMatrixMenuItems(menu, card) {",
  "  var actions = [",
  '    { key: "delete", label: "delete" },',
  '    { key: "skip", label: "skip" },',
  '    { key: "done", label: "done" },',
  "  ];",
  '  var working = card && card.classList.contains("task-card--working");',
  '  actions.push({ key: "working", label: working ? "working: on" : "working: off" });',
  "  actions.forEach(function (action) {",
  '    var item = document.createElement("button");',
  '    item.type = "button";',
  '    item.className = "matrix-menu-item matrix-menu-item--" + action.key;',
  "    item.textContent = action.label;",
  '    item.setAttribute("data-matrix-action", action.key);',
  "    menu.appendChild(item);",
  "  });",
  "}",
  "var matrixModal = null;",
  "function closeMatrixModal() {",
  '  if (!matrixModal) return;',
  "  matrixModal.remove();",
  "  matrixModal = null;",
  "  matrixMenuCard = null;",
  "}",
  "function renderMatrixDeleteModal(card) {",
  '  var backdrop = document.createElement("div");',
  '  backdrop.className = "matrix-modal-backdrop";',
  '  var dialog = document.createElement("div");',
  '  dialog.className = "matrix-modal";',
  '  var message = document.createElement("p");',
  '  message.className = "matrix-modal-text";',
  '  message.textContent = "このタスクを削除しますか？";',
  "  dialog.appendChild(message);",
  '  var row = document.createElement("div");',
  '  row.className = "matrix-modal-actions";',
  '  var cancelButton = document.createElement("button");',
  '  cancelButton.type = "button";',
  '  cancelButton.className = "matrix-modal-button matrix-modal-button--cancel";',
  '  cancelButton.textContent = "キャンセル";',
  '  cancelButton.setAttribute("data-matrix-modal-action", "cancel");',
  "  row.appendChild(cancelButton);",
  '  var confirmButton = document.createElement("button");',
  '  confirmButton.type = "button";',
  '  confirmButton.className = "matrix-modal-button matrix-modal-button--danger";',
  '  confirmButton.textContent = "削除";',
  '  confirmButton.setAttribute("data-matrix-modal-action", "confirm");',
  "  row.appendChild(confirmButton);",
  "  dialog.appendChild(row);",
  '  backdrop.addEventListener("click", function (event) {',
  '    var button = event.target.closest ? event.target.closest("[data-matrix-modal-action]") : null;',
  "    if (!button) return;",
  '    var action = button.getAttribute("data-matrix-modal-action");',
  '    if (action === "confirm") { setTimeout(function () { closeMatrixModal(); persistMatrixDelete(card); }, 0); return; }',
  '    if (action === "cancel") { setTimeout(function () { closeMatrixModal(); }, 0); return; }',
  "  });",
  "  backdrop.appendChild(dialog);",
  "  document.body.appendChild(backdrop);",
  "  matrixModal = backdrop;",
  "}",
  "function openMatrixMenu(card, x, y) {",
  "  closeMatrixMenu();",
  "  matrixMenuCard = card;",
  '  var taskId = card.getAttribute("data-task-id") || "";',
  '  var menu = document.createElement("div");',
  '  menu.className = "matrix-menu";',
  "  renderMatrixMenuItems(menu, card);",
  '  menu.addEventListener("click", function (event) {',
  '    var item = event.target.closest("[data-matrix-action]");',
  "    if (!item) return;",
  '    var action = item.getAttribute("data-matrix-action");',
  '    if (action === "done" || action === "skip") { persistMatrixStatus(matrixMenuCard, action); return; }',
  '    if (action === "working") {',
  '      var workingCard = matrixMenuCard;',
  '      var working = workingCard && !workingCard.classList.contains("task-card--working");',
  "      persistMatrixWorking(workingCard, working);",
  "      return;",
  "    }",
  '    if (action === "delete") {',
  '      var card = matrixMenuCard;',
  '      setTimeout(function () { closeMatrixMenu(); renderMatrixDeleteModal(card); }, 0);',
  "      return;",
  "    }",
  "  });",
  "  document.body.appendChild(menu);",
  "  var rect = menu.getBoundingClientRect();",
  "  menu.style.left = Math.max(8, Math.min(x, window.innerWidth - rect.width - 8)) + 'px';",
  "  menu.style.top = Math.max(8, Math.min(y, window.innerHeight - rect.height - 8)) + 'px';",
  "  matrixMenu = menu;",
  "  matrixMenuJustOpened = true;",
  "  void taskId;",
  "}",
  'document.addEventListener("contextmenu", function (event) {',
  '  var card = event.target.closest ? event.target.closest(".matrix-cards .task-card") : null;',
  "  if (!card || matrixActionPending) return;",
  "  event.preventDefault();",
  "  openMatrixMenu(card, event.clientX, event.clientY);",
  "});",
  'document.addEventListener("click", function (event) {',
  "  if (!matrixMenu) return;",
  "  if (matrixMenu.contains(event.target)) { matrixMenuJustOpened = false; return; }",
  "  if (matrixMenuJustOpened) { matrixMenuJustOpened = false; return; }",
  "  closeMatrixMenu();",
  "}, true);",
].join("\n");

export const Layout: FC<{ active: "matrix" | "tasks"; children?: JSX.Element }> = ({
  active,
  children,
}) => (
  <html lang="ja">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{BRAND_NAME}</title>
      <link rel="stylesheet" href="/styles.css" />
      <script src={HTMX_SCRIPT} defer></script>
      <script src="/htmx-conflict.js" defer></script>
      <script src="/popover-dismiss.js" defer></script>
      <script src="/task-form-shortcut.js" defer></script>
      <script src="/description-editor.js" defer></script>
      <script src="/matrix-dnd.js" defer></script>
      <script src="/task-list-selection.js" defer></script>
    </head>
    <body>
      <header class="topbar">
        <a class="brand" href="/">{BRAND_NAME}</a>
        <nav class="nav" aria-label="Primary">
          <a class={active === "matrix" ? "active" : undefined} href="/">
            Matrix
          </a>
          <a class={active === "tasks" ? "active" : undefined} href="/tasks">
            Tasks
          </a>
        </nav>
        <form action="/logout" method="post" class="logout">
          <button type="submit" class="button">Logout</button>
        </form>
      </header>
      <main id="page">{children}</main>
    </body>
  </html>
);
