import type { FC } from "hono/jsx";
import type { JSX } from "hono/jsx/jsx-runtime";

const HTMX_SCRIPT = "https://cdn.jsdelivr.net/npm/htmx.org@2.0.4/dist/htmx.min.js";
export const HTMX_CONFLICT_SWAP_SCRIPT = [
  "document.body.addEventListener('htmx:beforeSwap', function (event) {",
  "  if (event.detail.xhr.status !== 409) return;",
  "  event.detail.shouldSwap = true;",
  "  event.detail.isError = false;",
  "});",
].join("\n");
export const POPOVER_DISMISS_SCRIPT = [
  "document.addEventListener('click', function (event) {",
  "  var target = event.target;",
  "  var cancel = target && target.closest ? target.closest('[data-popover-cancel]') : null;",
  "  Array.prototype.forEach.call(document.querySelectorAll('[data-popover-close][open]'), function (details) {",
  "    if (cancel ? details.contains(cancel) : !details.contains(target)) details.removeAttribute('open');",
  "  });",
  "  var panel = document.querySelector('[data-popover-close-href]');",
  "  if (!panel || panel.contains(event.target)) return;",
  "  var href = panel.getAttribute('data-popover-close-href');",
  "  if (href) window.location.assign(href);",
  "});",
  "document.addEventListener('change', function (event) {",
  "  var target = event.target;",
  "  var details = target && target.closest ? target.closest('[data-popover-close]') : null;",
  "  if (details) details.removeAttribute('open');",
  "});",
].join("\n");
export const MATRIX_DND_SCRIPT = [
  "var matrixDraggingCard = null;",
  "var matrixDropTarget = null;",
  "var matrixDndPending = false;",
  "var suppressMatrixCardClick = false;",
  "function showDndConflict() {",
  '  var notice = document.getElementById("dnd-conflict");',
  "  if (notice) notice.hidden = false;",
  "}",
  "function restoreMatrix() {",
  '  fetch("/", { headers: { "HX-Request": "true" } })',
  "    .then(function (response) { return response.text(); })",
  "    .then(function (html) {",
  '      var page = document.getElementById("page");',
  "      if (page) page.innerHTML = html;",
  "      showDndConflict();",
  "      initMatrixDnd();",
  "    });",
  "}",
  "function matrixCards(list) {",
  '  return Array.prototype.slice.call(list.querySelectorAll(":scope > .task-card"));',
  "}",
  "function matrixDropIndex(list, pointerY) {",
  "  var cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  for (var index = 0; index < cards.length; index += 1) {",
  "    var box = cards[index].getBoundingClientRect();",
  "    if (pointerY < box.top + box.height / 2) return index;",
  "  }",
  "  return cards.length;",
  "}",
  "function setMatrixDropTarget(target) {",
  "  if (matrixDropTarget === target) return;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.remove("drop-target");',
  "  matrixDropTarget = target;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.add("drop-target");',
  "}",
  "function clearMatrixDnd() {",
  '  if (matrixDraggingCard) matrixDraggingCard.classList.remove("dragging");',
  "  setMatrixDropTarget(null);",
  "  matrixDraggingCard = null;",
  "}",
  "function setMatrixDndPending(pending) {",
  "  matrixDndPending = pending;",
  '  document.querySelectorAll(".matrix-cards .task-card").forEach(function (card) {',
  '    card.setAttribute("draggable", pending ? "false" : "true");',
  "  });",
  "}",
  "function persistMatrixDrop(card, target) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  '  var area = target.getAttribute("data-area");',
  "  var order = matrixCards(target).indexOf(card);",
  "  if (!taskId || !version || area === null || order < 0) return;",
  "  setMatrixDndPending(true);",
  '  return fetch("/api/tasks/reorder", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ id: taskId, area: Number(area), order: order, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) { showDndConflict(); restoreMatrix(); return null; }",
  "    return response.json();",
  "  }).then(function (tasks) {",
  "    if (!Array.isArray(tasks)) return;",
  "    tasks.forEach(function (task) {",
  '      if (!task || typeof task.id !== "string" || typeof task.version !== "number") return;',
  '      document.querySelectorAll(".task-card[data-task-id]").forEach(function (updatedCard) {',
  '        if (updatedCard.getAttribute("data-task-id") === task.id) {',
  '          updatedCard.setAttribute("data-version", String(task.version));',
  "        }",
  "      });",
  "    });",
  "  }).finally(function () { setMatrixDndPending(false); });",
  "}",
  "function initMatrixDnd() {",
  '  var lists = document.querySelectorAll(".matrix-cards[data-dnd-group]");',
  "  lists.forEach(function (list) {",
  '    list.querySelectorAll(".task-card").forEach(function (card) {',
  '      card.setAttribute("draggable", matrixDndPending ? "false" : "true");',
  "    });",
  "  });",
  "}",
  'document.addEventListener("dragstart", function (event) {',
  '  var card = event.target.closest(".matrix-cards .task-card");',
  "  if (!card || !event.dataTransfer) return;",
  "  if (matrixDndPending) { event.preventDefault(); return; }",
  "  matrixDraggingCard = card;",
  '  event.dataTransfer.setData("text/plain", card.getAttribute("data-task-id") || "");',
  '  event.dataTransfer.effectAllowed = "move";',
  '  card.classList.add("dragging");',
  "});",
  'document.addEventListener("dragover", function (event) {',
  '  var target = event.target.closest(".matrix-cards[data-dnd-group]");',
  "  if (!matrixDraggingCard || !target) return;",
  "  event.preventDefault();",
  '  event.dataTransfer.dropEffect = "move";',
  "  setMatrixDropTarget(target);",
  "});",
  'document.addEventListener("drop", function (event) {',
  '  var target = event.target.closest(".matrix-cards[data-dnd-group]");',
  "  if (!matrixDraggingCard || !target) return;",
  "  event.preventDefault();",
  "  var card = matrixDraggingCard;",
  "  var index = matrixDropIndex(target, event.clientY);",
  "  var cards = matrixCards(target).filter(function (candidate) { return candidate !== card; });",
  "  target.insertBefore(card, cards[index] || null);",
  "  suppressMatrixCardClick = true;",
  "  persistMatrixDrop(card, target);",
  "  clearMatrixDnd();",
  "});",
  'document.addEventListener("dragend", clearMatrixDnd);',
  'document.addEventListener("click", function (event) {',
  '  if (!suppressMatrixCardClick || !event.target.closest(".matrix-cards .task-card")) return;',
  "  event.preventDefault();",
  "  suppressMatrixCardClick = false;",
  "}, true);",
  'document.addEventListener("click", function (event) {',
  "  if (event.defaultPrevented) return;",
  '  if (event.target.closest("a, button, input, select, textarea")) return;',
  '  var quadrant = event.target.closest(".area--quadrant[data-drop-area]");',
  "  if (!quadrant) return;",
  '  var area = quadrant.getAttribute("data-drop-area");',
  "  if (area === null) return;",
  '  window.location.assign("/tasks/new?area=" + encodeURIComponent(area) + "&from=matrix");',
  "});",
  'document.addEventListener("DOMContentLoaded", initMatrixDnd);',
  'document.addEventListener("htmx:load", initMatrixDnd);',
  "var matrixMenu = null;",
  "var matrixMenuCard = null;",
  "var matrixActionPending = false;",
  "function closeMatrixMenu() {",
  '  if (!matrixMenu) return;',
  "  matrixMenu.remove();",
  "  matrixMenu = null;",
  "  matrixMenuCard = null;",
  "}",
  "function removeMatrixCard(card) {",
  "  if (card) card.remove();",
  "  matrixMenuCard = null;",
  "}",
  "function setMatrixActionPending(pending) {",
  "  matrixActionPending = pending;",
  "  setMatrixDndPending(pending);",
  "}",
  "function restoreMatrixAfterAction() {",
  "  showDndConflict();",
  "  return restoreMatrix();",
  "}",
  "function persistMatrixStatus(card, status) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  closeMatrixMenu();",
  "  setMatrixActionPending(true);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "PATCH",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ status: status, version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) removeMatrixCard(card);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function persistMatrixDelete(card) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "DELETE",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction();",
  "    removeMatrixCard(card);",
  "    return null;",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function renderMatrixMenuItems(menu) {",
  "  var actions = [",
  '    { key: "done", label: "done" },',
  '    { key: "skip", label: "skip" },',
  '    { key: "delete", label: "delete" },',
  "  ];",
  "  actions.forEach(function (action) {",
  '    var item = document.createElement("button");',
  '    item.type = "button";',
  '    item.className = "matrix-menu-item matrix-menu-item--" + action.key;',
  "    item.textContent = action.label;",
  '    item.setAttribute("data-matrix-action", action.key);',
  "    menu.appendChild(item);",
  "  });",
  "}",
  "var matrixModal = null;",
  "function closeMatrixModal() {",
  '  if (!matrixModal) return;',
  "  matrixModal.remove();",
  "  matrixModal = null;",
  "  matrixMenuCard = null;",
  "}",
  "function renderMatrixDeleteModal(card) {",
  '  var backdrop = document.createElement("div");',
  '  backdrop.className = "matrix-modal-backdrop";',
  '  var dialog = document.createElement("div");',
  '  dialog.className = "matrix-modal";',
  '  var message = document.createElement("p");',
  '  message.className = "matrix-modal-text";',
  '  message.textContent = "このタスクを削除しますか？";',
  "  dialog.appendChild(message);",
  '  var row = document.createElement("div");',
  '  row.className = "matrix-modal-actions";',
  '  var cancelButton = document.createElement("button");',
  '  cancelButton.type = "button";',
  '  cancelButton.className = "matrix-modal-button matrix-modal-button--cancel";',
  '  cancelButton.textContent = "キャンセル";',
  '  cancelButton.setAttribute("data-matrix-modal-action", "cancel");',
  "  row.appendChild(cancelButton);",
  '  var confirmButton = document.createElement("button");',
  '  confirmButton.type = "button";',
  '  confirmButton.className = "matrix-modal-button matrix-modal-button--danger";',
  '  confirmButton.textContent = "削除";',
  '  confirmButton.setAttribute("data-matrix-modal-action", "confirm");',
  "  row.appendChild(confirmButton);",
  "  dialog.appendChild(row);",
  '  backdrop.addEventListener("click", function (event) {',
  '    var button = event.target.closest ? event.target.closest("[data-matrix-modal-action]") : null;',
  "    if (!button) return;",
  '    var action = button.getAttribute("data-matrix-modal-action");',
  '    if (action === "confirm") { closeMatrixModal(); persistMatrixDelete(card); return; }',
  '    if (action === "cancel") { closeMatrixModal(); return; }',
  "  });",
  "  backdrop.appendChild(dialog);",
  "  document.body.appendChild(backdrop);",
  "  matrixModal = backdrop;",
  "}",
  "function openMatrixMenu(card, x, y) {",
  "  closeMatrixMenu();",
  "  matrixMenuCard = card;",
  '  var taskId = card.getAttribute("data-task-id") || "";',
  '  var menu = document.createElement("div");',
  '  menu.className = "matrix-menu";',
  "  renderMatrixMenuItems(menu);",
  '  menu.addEventListener("click", function (event) {',
  '    var item = event.target.closest("[data-matrix-action]");',
  "    if (!item) return;",
  '    var action = item.getAttribute("data-matrix-action");',
  '    if (action === "done" || action === "skip") { persistMatrixStatus(matrixMenuCard, action); return; }',
  '    if (action === "delete") { var card = matrixMenuCard; closeMatrixMenu(); renderMatrixDeleteModal(card); return; }',
  "  });",
  "  document.body.appendChild(menu);",
  "  var rect = menu.getBoundingClientRect();",
  "  menu.style.left = Math.max(8, Math.min(x, window.innerWidth - rect.width - 8)) + 'px';",
  "  menu.style.top = Math.max(8, Math.min(y, window.innerHeight - rect.height - 8)) + 'px';",
  "  matrixMenu = menu;",
  "  void taskId;",
  "}",
  'document.addEventListener("contextmenu", function (event) {',
  '  var card = event.target.closest ? event.target.closest(".matrix-cards .task-card") : null;',
  "  if (!card || matrixActionPending) return;",
  "  event.preventDefault();",
  "  openMatrixMenu(card, event.clientX, event.clientY);",
  "});",
  'document.addEventListener("click", function (event) {',
  "  if (matrixMenu && !matrixMenu.contains(event.target)) closeMatrixMenu();",
  "}, true);",
  'document.addEventListener("scroll", function () { closeMatrixMenu(); }, true);',
].join("\n");

export const Layout: FC<{ active: "matrix" | "tasks"; children?: JSX.Element }> = ({
  active,
  children,
}) => (
  <html lang="ja">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>SIFTQ</title>
      <link rel="stylesheet" href="/styles.css" />
      <script src={HTMX_SCRIPT} defer></script>
      <script src="/htmx-conflict.js" defer></script>
      <script src="/popover-dismiss.js" defer></script>
      <script src="/matrix-dnd.js" defer></script>
    </head>
    <body>
      <header class="topbar">
        <a class="brand" href="/">SIFTQ</a>
        <nav class="nav" aria-label="Primary">
          <a class={active === "matrix" ? "active" : undefined} href="/">
            Matrix
          </a>
          <a class={active === "tasks" ? "active" : undefined} href="/tasks">
            Tasks
          </a>
        </nav>
      </header>
      <main id="page">{children}</main>
    </body>
  </html>
);
