
export const HTMX_CONFLICT_SWAP_SCRIPT = [
  "document.body.addEventListener('htmx:beforeSwap', function (event) {",
  "  if (event.detail.xhr.status !== 409) return;",
  "  event.detail.shouldSwap = true;",
  "  event.detail.isError = false;",
  "});",
].join("\n");
export const POPOVER_DISMISS_SCRIPT = [
  "document.addEventListener('click', function (event) {",
  "  var target = event.target;",
  "  var cancel = target && target.closest ? target.closest('[data-popover-cancel]') : null;",
  "  Array.prototype.forEach.call(document.querySelectorAll('[data-popover-close][open]'), function (details) {",
  "    if (cancel ? details.contains(cancel) : !details.contains(target)) details.removeAttribute('open');",
  "  });",
  "  var panel = document.querySelector('[data-popover-close-href]');",
  "  if (!panel || panel.contains(event.target)) return;",
  "  var href = panel.getAttribute('data-popover-close-href');",
  "  if (href) window.location.assign(href);",
  "});",
  "document.addEventListener('change', function (event) {",
  "  var target = event.target;",
  "  var details = target && target.closest ? target.closest('[data-popover-close]') : null;",
  "  if (details) details.removeAttribute('open');",
  "});",
].join("\n");
export const TASK_FORM_SHORTCUT_SCRIPT = [
  'document.addEventListener("keydown", function (event) {',
  '  if (!event.ctrlKey || event.key !== "Enter") return;',
  "  var target = event.target;",
  '  var editor = target && target.closest ? target.closest("[data-description-editor]") : null;',
  '  var isDescriptionEditor = Boolean(editor);',
  '  if (!target || (!isDescriptionEditor && target.name !== "title" && target.name !== "description")) return;',
  '  var form = target.closest ? target.closest("form[data-task-form]") : null;',
  "  if (!form) return;",
  "  event.preventDefault();",
  '  if (form.dataset.shortcutSubmitting === "true") return;',
  "  if (!form.checkValidity()) { form.reportValidity(); return; }",
  '  form.dataset.shortcutSubmitting = "true";',
  "  form.requestSubmit();",
  "});",
  'window.addEventListener("pageshow", function (event) {',
  "  if (!event.persisted) return;",
  "  if (!document.querySelector('form[data-task-form=\"edit\"]')) return;",
  "  window.location.reload();",
  "});",
].join("\n");
export const DESCRIPTION_EDITOR_SCRIPT = [
  "function descriptionEditorValue(editor) {",
  '  return editor.innerText.replace(/\\n$/, "");',
  "}",
  "function syncDescriptionEditor(editor) {",
  '  var form = editor.closest("form");',
  '  var hidden = form ? form.querySelector("textarea[data-description-value]") : null;',
  '  if (hidden) hidden.value = descriptionEditorValue(editor);',
  "}",
  "function linkifyDescriptionEditor(editor) {",
  '  var walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);',
  "  var nodes = [];",
  "  while (walker.nextNode()) nodes.push(walker.currentNode);",
  "  nodes.forEach(function (node) {",
  '    if (!node.parentElement || node.parentElement.closest("a")) return;',
  "    var text = node.nodeValue || \"\";",
  '    var pattern = /https?:\\/\\/[^\\s<>]+/g;',
  "    var match;",
  "    var cursor = 0;",
  "    var fragment = document.createDocumentFragment();",
  "    var changed = false;",
  "    while ((match = pattern.exec(text)) !== null) {",
  "      var raw = match[0];",
  '      var url = raw.replace(/[.,!?;:]+$/, "");',
  "      if (!url) continue;",
  "      if (match.index > cursor) fragment.appendChild(document.createTextNode(text.slice(cursor, match.index)));",
  "      var link = document.createElement(\"a\");",
  "      link.href = url;",
  "      link.textContent = url;",
  "      fragment.appendChild(link);",
  "      if (raw.length > url.length) fragment.appendChild(document.createTextNode(raw.slice(url.length)));",
  "      cursor = match.index + raw.length;",
  "      changed = true;",
  "    }",
  "    if (!changed) return;",
  "    if (cursor < text.length) fragment.appendChild(document.createTextNode(text.slice(cursor)));",
  "    node.parentNode.replaceChild(fragment, node);",
  "  });",
  "}",
  "function initializeDescriptionEditors() {",
  '  document.querySelectorAll("[data-description-editor]").forEach(function (editor) {',
  '    if (editor.dataset.descriptionEditorInitialized === "true") { syncDescriptionEditor(editor); return; }',
  '    editor.dataset.descriptionEditorInitialized = "true";',
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  '    editor.addEventListener("input", function () { syncDescriptionEditor(editor); });',
  '    editor.addEventListener("click", function (event) {',
  '      var link = event.target && event.target.closest ? event.target.closest("a") : null;',
  '      if (!link || !editor.contains(link)) return;',
  "      event.preventDefault();",
  "      if (event.ctrlKey || event.metaKey) {",
  '        window.open(link.href, "_blank", "noopener,noreferrer");',
  "      } else {",
  "        window.location.assign(link.href);",
  "      }",
  "    });",
  '    editor.addEventListener("paste", function (event) {',
  '      var text = event.clipboardData ? event.clipboardData.getData("text/plain") : "";',
  "      if (!text) return;",
  "      event.preventDefault();",
  '      document.execCommand("insertText", false, text);',
  "      linkifyDescriptionEditor(editor);",
  "      syncDescriptionEditor(editor);",
  "    });",
  "  });",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeDescriptionEditors);',
  'document.addEventListener("htmx:load", initializeDescriptionEditors);',
  "function taskFormDraftKey(form) {",
  '  if (form.getAttribute("data-task-form") === "new") return null;',
  '  var action = form.getAttribute("action") || "";',
  '  var match = action.match(/\\/tasks\\/([^/?#]+)/);',
  '  if (match) return "siftq.task-draft:" + decodeURIComponent(match[1]);',
  "  return null;",
  "}",
  "function removeTaskDraft(taskId) {",
  '  if (!taskId) return;',
  '  try { localStorage.removeItem("siftq.task-draft:" + taskId); } catch (e) {}',
  "}",
  "function taskFormDraftVersion(form) {",
  '  var versionInput = form.querySelector("#task-version");',
  "  if (!versionInput) return null;",
  "  var version = Number(versionInput.value);",
  '  return Number.isFinite(version) ? version : null;',
  "}",
  "function saveTaskFormDraft(form) {",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  '  var titleInput = form.querySelector(\'input[name="title"]\');',
  '  var hidden = form.querySelector("textarea[data-description-value]");',
  '  var editor = form.querySelector("[data-description-editor]");',
  "  var title = titleInput ? titleInput.value : \"\";",
  "  var description = hidden ? hidden.value : editor ? descriptionEditorValue(editor) : \"\";",
  "  var draft = { title: title, description: description, updatedAt: Date.now() };",
  "  var version = taskFormDraftVersion(form);",
  "  if (version !== null) draft.version = version;",
  "  try {",
  "    localStorage.setItem(key, JSON.stringify(draft));",
  "  } catch (e) {}",
  "}",
  "function scheduleTaskFormDraft(form) {",
  "  if (form._taskDraftTimer) clearTimeout(form._taskDraftTimer);",
  "  form._taskDraftTimer = setTimeout(function () { saveTaskFormDraft(form); }, 500);",
  "}",
  "function restoreTaskFormDraft(form) {",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  var raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  var draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  '  if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  "  if (typeof draft.updatedAt === 'number' && Date.now() - draft.updatedAt >= 24 * 60 * 60 * 1000) {",
  "    try { localStorage.removeItem(key); } catch (e) {}",
  "    return;",
  "  }",
  "  if (typeof draft.version === 'number') {",
  "    var serverVersion = taskFormDraftVersion(form);",
  "    if (serverVersion !== null && serverVersion !== draft.version) {",
  "      try { localStorage.removeItem(key); } catch (e) {}",
  "      return;",
  "    }",
  "  }",
  '  var titleInput = form.querySelector(\'input[name="title"]\');',
  "  if (titleInput) titleInput.value = draft.title;",
  '  var editor = form.querySelector("[data-description-editor]");',
  "  if (editor) {",
  "    editor.textContent = draft.description;",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "  } else {",
  '    var hidden = form.querySelector("textarea[data-description-value]");',
  "    if (hidden) hidden.value = draft.description;",
  "  }",
  "}",
  "function initializeTaskFormDrafts() {",
  '  document.querySelectorAll("form[data-task-form]").forEach(function (form) {',
  '    if (form.dataset.taskDraftInitialized === "true") return;',
  '    form.dataset.taskDraftInitialized = "true";',
  "    restoreTaskFormDraft(form);",
  '    form.addEventListener("input", function () { scheduleTaskFormDraft(form); });',
  "  });",
  "}",
  "function refreshTaskFormDraftVersion() {",
  '  var form = document.querySelector(\'form[data-task-form="edit"]\');',
  "  if (!form) return;",
  "  var version = taskFormDraftVersion(form);",
  "  if (version === null) return;",
  "  var key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  var raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  var draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  '  if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  "  if (draft.version === version) return;",
  "  draft.version = version;",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (e) {}",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeTaskFormDrafts);',
  'document.addEventListener("htmx:load", initializeTaskFormDrafts);',
  'document.body.addEventListener("htmx:oobAfterSwap", refreshTaskFormDraftVersion);',
  'document.body.addEventListener("htmx:afterSettle", refreshTaskFormDraftVersion);',
  'document.body.addEventListener("htmx:afterRequest", function (event) {',
  '  var detail = event.detail || {};',
  '  var xhr = detail.xhr;',
  '  var status = xhr ? xhr.status : 0;',
  '  if (status < 200 || status >= 300) return;',
  '  try { if (xhr && typeof xhr.getResponseHeader === "function" && !xhr.getResponseHeader("HX-Redirect")) return; } catch (e) { return; }',
  '  var elt = detail.elt;',
  '  var form = elt && elt.closest ? elt.closest("form[data-task-form]") : null;',
  '  if (!form) return;',
  '  if (form._taskDraftTimer) { clearTimeout(form._taskDraftTimer); form._taskDraftTimer = null; }',
  '  var key = taskFormDraftKey(form);',
  '  if (!key) return;',
  '  try { localStorage.removeItem(key); } catch (e) {}',
  '});',
  'document.addEventListener("submit", function (event) {',
  '  var form = event.target;',
  '  if (!form || !form.matches || !form.matches(\'form[action="/logout"]\')) return;',
  "  try {",
  "    var remove = [];",
  "    for (var i = 0; i < localStorage.length; i += 1) {",
  "      var key = localStorage.key(i);",
  '      if (key && key.indexOf("siftq.task-draft:") === 0) remove.push(key);',
  "    }",
  "    remove.forEach(function (key) { localStorage.removeItem(key); });",
  "  } catch (e) {}",
  "});",
].join("\n");
export const TASK_LIST_SELECTION_SCRIPT = [
  "function initializeTaskListSelection() {",
  '  var list = document.querySelector("[data-task-list]");',
  '  if (!list || list.dataset.selectionInitialized === "true") return;',
  '  list.dataset.selectionInitialized = "true";',
  '  var selectAll = list.querySelector("[data-task-select-all]");',
  '  var statusTabs = list.querySelector("[data-task-status-tabs]");',
  '  var selectionSummary = list.querySelector("[data-task-selection-summary]");',
  '  var actionButtons = list.querySelectorAll("[data-task-action]");',
  '  var feedback = list.querySelector("[data-task-selection-feedback]");',
  "  var actionPending = false;",
  '  var selects = function () { return Array.prototype.slice.call(list.querySelectorAll("[data-task-select]")); };',
  "  function selectedInputs() {",
  '    return selects().filter(function (checkbox) { return checkbox.checked; }).map(function (checkbox) {',
  '      var row = checkbox.closest("[data-task-row]");',
  '      var id = row && row.getAttribute("data-task-id");',
  '      var version = row && row.getAttribute("data-version");',
  '      if (!id || !version) return null;',
  '      return { id: id, version: Number(version) };',
  '    }).filter(function (input) { return input !== null; });',
  "  }",
  "  function showFeedback(message) {",
  '    if (!feedback) return;',
  '    feedback.hidden = false;',
  '    feedback.classList.add("error");',
  '    feedback.textContent = message;',
  "  }",
  "  function setPending(pending) {",
  "    actionPending = pending;",
  '    actionButtons.forEach(function (button) { button.disabled = pending || selectedInputs().length === 0; });',
  '    if (selectAll) selectAll.disabled = pending || selects().length === 0;',
  "  }",
  "  function syncSelection() {",
  "    var checkboxes = selects();",
  '    var selected = checkboxes.filter(function (checkbox) { return checkbox.checked; });',
  '    if (selectAll) { selectAll.checked = checkboxes.length > 0 && selected.length === checkboxes.length; selectAll.indeterminate = selected.length > 0 && selected.length < checkboxes.length; selectAll.disabled = actionPending || checkboxes.length === 0; }',
  '    if (statusTabs) statusTabs.hidden = selected.length > 0;',
  '    if (selectionSummary) { selectionSummary.hidden = selected.length === 0; selectionSummary.textContent = selected.length + " of " + checkboxes.length + " selected"; }',
  '    actionButtons.forEach(function (button) { button.disabled = actionPending || selected.length === 0; });',
  '    list.querySelectorAll("[data-task-row]").forEach(function (row) {',
  '      var checkbox = row.querySelector("[data-task-select]");',
  '      if (checkbox) row.classList.toggle("is-selected", checkbox.checked);',
  "    });",
  "  }",
  '  if (selectAll) selectAll.addEventListener("change", function () { selects().forEach(function (checkbox) { checkbox.checked = selectAll.checked; }); syncSelection(); });',
  '  list.addEventListener("change", function (event) { if (event.target.matches("[data-task-select]")) syncSelection(); });',
  "  function submitBulkAction(action, inputs) {",
  "    setPending(true);",
  '    var isDelete = action === "delete";',
  '    var request = fetch(isDelete ? "/api/tasks/bulk" : "/api/tasks/bulk/status", {',
  '      method: isDelete ? "DELETE" : "PATCH",',
  '      headers: { "Content-Type": "application/json" },',
  '      body: JSON.stringify(isDelete ? { tasks: inputs } : { status: action, tasks: inputs }),',
  "    });",
  '    request.then(function (response) {',
  '      if (!response.ok) { showFeedback(response.status === 409 ? "Task was updated elsewhere. Reload the list." : "Bulk action failed."); return false; }',
  '      return true;',
  '    }).then(function (succeeded) { if (succeeded) { if (isDelete && typeof removeTaskDraft === "function") inputs.forEach(function (input) { removeTaskDraft(input.id); }); window.location.reload(); } }).catch(function () { showFeedback("Bulk action failed."); }).finally(function () { setPending(false); });',
  "  }",
  "  function renderDeleteDialog(inputs) {",
  '    var backdrop = document.createElement("div");',
  '    backdrop.className = "matrix-modal-backdrop";',
  '    var dialog = document.createElement("div");',
  '    dialog.className = "matrix-modal";',
  '    var message = document.createElement("p");',
  '    message.className = "matrix-modal-text";',
  '    message.textContent = "選択した" + inputs.length + "件のタスクを削除しますか？";',
  '    dialog.appendChild(message);',
  '    var row = document.createElement("div");',
  '    row.className = "matrix-modal-actions";',
  '    ["キャンセル", "削除"].forEach(function (label, index) {',
  '      var button = document.createElement("button");',
  '      button.type = "button";',
  '      button.className = "matrix-modal-button " + (index === 1 ? "matrix-modal-button--danger" : "matrix-modal-button--cancel");',
  '      button.textContent = label;',
  '      button.setAttribute("data-task-list-delete", index === 1 ? "confirm" : "cancel");',
  '      row.appendChild(button);',
  '    });',
  '    dialog.appendChild(row);',
  '    backdrop.addEventListener("click", function (event) {',
  '      var button = event.target.closest ? event.target.closest("[data-task-list-delete]") : null;',
  '      if (!button) return;',
  '      backdrop.remove();',
  '      if (button.getAttribute("data-task-list-delete") === "confirm") submitBulkAction("delete", inputs);',
  '    });',
  '    backdrop.appendChild(dialog);',
  '    document.body.appendChild(backdrop);',
  "  }",
  '  list.addEventListener("click", function (event) {',
  '    var action = event.target.closest ? event.target.closest("[data-task-action]") : null;',
  '    if (!action) return;',
  '    var inputs = selectedInputs();',
  '    if (actionPending || inputs.length === 0) return;',
  '    event.preventDefault();',
  '    var actionName = action.getAttribute("data-task-action");',
  '    var menu = action.closest(".task-bulk-menu");',
  '    if (menu) menu.removeAttribute("open");',
  '    if (actionName === "delete") { renderDeleteDialog(inputs); return; }',
  '    if (actionName === "do" || actionName === "done" || actionName === "skip") submitBulkAction(actionName, inputs);',
  "  });",
  "  syncSelection();",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeTaskListSelection);',
  'document.addEventListener("htmx:load", initializeTaskListSelection);',
].join("\n");
export const MATRIX_DND_SCRIPT = [
  "var matrixDraggingCard = null;",
  "var matrixDragPointerId = null;",
  "var matrixDragStart = null;",
  "var matrixDropTarget = null;",
  "var matrixDndPending = false;",
  "var suppressMatrixCardClick = false;",
  "var matrixAutoScrollFrame = null;",
  "var matrixAutoScrollList = null;",
  "var matrixAutoScrollDelta = 0;",
  "var matrixDragGhost = null;",
  "var matrixDragPlaceholder = null;",
  "var matrixDragGrabOffset = null;",
  "var MATRIX_DRAG_THRESHOLD = 5;",
  "function showDndConflict() {",
  '  var notice = document.getElementById("dnd-conflict");',
  "  if (notice) notice.hidden = false;",
  "}",
  "function restoreMatrix() {",
  '  fetch("/", { headers: { "HX-Request": "true" } })',
  "    .then(function (response) { return response.text(); })",
  "    .then(function (html) {",
  '      var page = document.getElementById("page");',
  "      if (page) page.innerHTML = html;",
  "      showDndConflict();",
  "      initMatrixDnd();",
  "    });",
  "}",
  "function matrixCards(list) {",
  '  return Array.prototype.slice.call(list.querySelectorAll(":scope > .task-card"));',
  "}",
  "function matrixDropIndex(list, pointerY) {",
  "  var cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  for (var index = 0; index < cards.length; index += 1) {",
  "    var box = cards[index].getBoundingClientRect();",
  "    if (pointerY < box.top + box.height / 2) return index;",
  "  }",
  "  return cards.length;",
  "}",
  "function matrixDropListFromPoint(x, y) {",
  "  var element = document.elementFromPoint(x, y);",
  '  var quadrant = element && element.closest ? element.closest(".area--quadrant[data-drop-area]") : null;',
  '  return quadrant ? quadrant.querySelector(".matrix-cards[data-dnd-group]") : null;',
  "}",
  "function setMatrixDropTarget(target) {",
  "  if (matrixDropTarget === target) return;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.remove("drop-target");',
  "  matrixDropTarget = target;",
  '  if (matrixDropTarget) matrixDropTarget.closest(".area--quadrant").classList.add("drop-target");',
  "}",
  "function stopMatrixAutoScroll() {",
  "  if (matrixAutoScrollFrame !== null) {",
  "    window.cancelAnimationFrame(matrixAutoScrollFrame);",
  "    matrixAutoScrollFrame = null;",
  "  }",
  "  matrixAutoScrollList = null;",
  "  matrixAutoScrollDelta = 0;",
  "}",
  "function stepMatrixAutoScroll() {",
  "  matrixAutoScrollFrame = null;",
  "  if (!matrixAutoScrollList || matrixAutoScrollDelta === 0) return;",
  "  matrixAutoScrollList.scrollTop += matrixAutoScrollDelta * 14;",
  "  matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function updateMatrixAutoScroll(pointerY, list) {",
  "  if (!list || list.scrollHeight <= list.clientHeight) { stopMatrixAutoScroll(); return; }",
  "  var box = list.getBoundingClientRect();",
  "  var edge = 32;",
  "  var delta = pointerY < box.top + edge ? -1 : pointerY > box.bottom - edge ? 1 : 0;",
  "  if (delta === 0) { stopMatrixAutoScroll(); return; }",
  "  matrixAutoScrollList = list;",
  "  matrixAutoScrollDelta = delta;",
  "  if (matrixAutoScrollFrame === null) matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function clearMatrixDnd() {",
  '  if (matrixDraggingCard) matrixDraggingCard.classList.remove("dragging");',
  "  if (matrixDragGhost) { matrixDragGhost.remove(); matrixDragGhost = null; }",
  "  if (matrixDragPlaceholder) { matrixDragPlaceholder.remove(); matrixDragPlaceholder = null; }",
  "  matrixDragGrabOffset = null;",
  "  setMatrixDropTarget(null);",
  "  stopMatrixAutoScroll();",
  "  matrixDraggingCard = null;",
  "  matrixDragPointerId = null;",
  "  matrixDragStart = null;",
  "}",
  "function setMatrixDndPending(pending) {",
  "  matrixDndPending = pending;",
  "}",
  "function matrixCardFromEvent(event) {",
  "  var element = event.target;",
  '  return element && element.closest ? element.closest(".matrix-cards .task-card") : null;',
  "}",
  "function positionMatrixGhost(x, y) {",
  "  if (!matrixDragGhost || !matrixDragGrabOffset) return;",
  "  matrixDragGhost.style.left = (x - matrixDragGrabOffset.x) + 'px';",
  "  matrixDragGhost.style.top = (y - matrixDragGrabOffset.y) + 'px';",
  "}",
  "function positionMatrixPlaceholder(list, pointerY) {",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  if (!list || !matrixDragPlaceholder) return;",
  "  var cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  var index = matrixDropIndex(list, pointerY);",
  "  list.insertBefore(matrixDragPlaceholder, cards[index] || null);",
  "}",
  "function updateMatrixDrag(event) {",
  "  positionMatrixGhost(event.clientX, event.clientY);",
  "  var target = matrixDropListFromPoint(event.clientX, event.clientY);",
  "  setMatrixDropTarget(target);",
  "  positionMatrixPlaceholder(target, event.clientY);",
  "  updateMatrixAutoScroll(event.clientY, target);",
  "}",
  "function startMatrixDrag(event) {",
  '  matrixDraggingCard.classList.add("dragging");',
  "  suppressMatrixCardClick = true;",
  "  try { matrixDraggingCard.setPointerCapture(matrixDragPointerId); } catch (error) {}",
  "  var rect = matrixDraggingCard.getBoundingClientRect();",
  "  matrixDragGrabOffset = { x: event.clientX - rect.left, y: event.clientY - rect.top };",
  '  var ghost = matrixDraggingCard.cloneNode(true);',
  '  ghost.classList.remove("dragging");',
  '  ghost.classList.add("matrix-drag-ghost");',
  '  ghost.style.width = rect.width + "px";',
  "  document.body.appendChild(ghost);",
  "  matrixDragGhost = ghost;",
  '  var placeholder = document.createElement("div");',
  '  placeholder.className = "drop-line matrix-drag-placeholder";',
  '  placeholder.style.height = rect.height + "px";',
  "  matrixDragPlaceholder = placeholder;",
  "  updateMatrixDrag(event);",
  "}",
  "function finishMatrixDrag(event) {",
  "  var card = matrixDraggingCard;",
  "  var target = matrixDropTarget;",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  var index = target ? matrixDropIndex(target, event.clientY) : 0;",
  "  clearMatrixDnd();",
  "  setTimeout(function () { suppressMatrixCardClick = false; }, 0);",
  "  if (!target) return;",
  "  var cards = matrixCards(target).filter(function (candidate) { return candidate !== card; });",
  "  var reference = cards[index] || null;",
  "  target.insertBefore(card, reference);",
  "  persistMatrixDrop(card, target);",
  "}",
  "function initMatrixDnd() {",
  "  clearMatrixDnd();",
  "}",
  "function persistMatrixDrop(card, target) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  '  var area = target.getAttribute("data-area");',
  "  var order = matrixCards(target).indexOf(card);",
  "  if (!taskId || !version || area === null || order < 0) return;",
  "  setMatrixDndPending(true);",
  '  return fetch("/api/tasks/reorder", {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  "    body: JSON.stringify({ id: taskId, area: Number(area), order: order, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) { showDndConflict(); restoreMatrix(); return null; }",
  "    return response.json();",
  "  }).then(function (tasks) {",
  "    if (!Array.isArray(tasks)) return;",
  "    tasks.forEach(function (task) {",
  '      if (!task || typeof task.id !== "string" || typeof task.version !== "number") return;',
  '      document.querySelectorAll(".task-card[data-task-id]").forEach(function (updatedCard) {',
  '        if (updatedCard.getAttribute("data-task-id") === task.id) {',
  '          updatedCard.setAttribute("data-version", String(task.version));',
  "        }",
  "      });",
  "    });",
  "  }).finally(function () { setMatrixDndPending(false); });",
  "}",
  'document.addEventListener("pointerdown", function (event) {',
  "  if (event.button !== 0 || !event.isPrimary || matrixDndPending || matrixDraggingCard) return;",
  "  var card = matrixCardFromEvent(event);",
  '  if (!card || !card.getAttribute("data-task-id")) return;',
  "  matrixDraggingCard = card;",
  "  matrixDragPointerId = event.pointerId;",
  "  matrixDragStart = { x: event.clientX, y: event.clientY };",
  "});",
  'document.addEventListener("pointermove", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  '  if (!matrixDraggingCard.classList.contains("dragging")) {',
  "    var dx = event.clientX - matrixDragStart.x;",
  "    var dy = event.clientY - matrixDragStart.y;",
  "    if (Math.abs(dx) < MATRIX_DRAG_THRESHOLD && Math.abs(dy) < MATRIX_DRAG_THRESHOLD) return;",
  "    startMatrixDrag(event);",
  "    return;",
  "  }",
  "  event.preventDefault();",
  "  updateMatrixDrag(event);",
  "});",
  'document.addEventListener("pointerup", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  '  if (matrixDraggingCard.classList.contains("dragging")) { finishMatrixDrag(event); return; }',
  "  clearMatrixDnd();",
  "});",
  'document.addEventListener("pointercancel", function (event) {',
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  "  clearMatrixDnd();",
  "});",
  'document.addEventListener("click", function (event) {',
  "  if (!suppressMatrixCardClick) return;",
  "  var card = matrixCardFromEvent(event);",
  "  if (!card) return;",
  "  event.preventDefault();",
  "  event.stopPropagation();",
  "  suppressMatrixCardClick = false;",
  "}, true);",
  'document.addEventListener("click", function (event) {',
  "  if (event.defaultPrevented) return;",
  '  if (event.target.closest("a, button, input, select, textarea")) return;',
  '  var quadrant = event.target.closest(".area--quadrant[data-drop-area]");',
  "  if (!quadrant) return;",
  '  var area = quadrant.getAttribute("data-drop-area");',
  "  if (area === null) return;",
  '  window.location.assign("/tasks/new?area=" + encodeURIComponent(area) + "&from=matrix");',
  "});",
  'document.addEventListener("DOMContentLoaded", initMatrixDnd);',
  'document.addEventListener("htmx:load", initMatrixDnd);',
  "var matrixMenu = null;",
  "var matrixMenuCard = null;",
  "var matrixActionPending = false;",
  "var matrixMenuJustOpened = false;",
  "function closeMatrixMenu() {",
  '  if (!matrixMenu) return;',
  "  matrixMenu.remove();",
  "  matrixMenu = null;",
  "  matrixMenuCard = null;",
  "  matrixMenuJustOpened = false;",
  "}",
  "function removeMatrixCard(card) {",
  "  if (card) card.remove();",
  "  matrixMenuCard = null;",
  "}",
  "function setMatrixActionPending(pending) {",
  "  matrixActionPending = pending;",
  "  setMatrixDndPending(pending);",
  "}",
  "function restoreMatrixAfterAction() {",
  "  showDndConflict();",
  "  return restoreMatrix();",
  "}",
  "function persistMatrixStatus(card, status) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "PATCH",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ status: status, version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) removeMatrixCard(card);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function setMatrixCardWorking(card, working, version) {",
  '  if (typeof version === "number") card.setAttribute("data-version", String(version));',
  '  var header = card.querySelector(".task-card-header");',
  '  var badge = card.querySelector(".working-badge");',
  "  if (working) {",
  '    card.classList.add("task-card--working");',
  "    if (!badge && header) {",
  '      badge = document.createElement("span");',
  '      badge.className = "working-badge";',
  '      badge.textContent = "working";',
  "      header.appendChild(badge);",
  "    }",
  "  } else {",
  '    card.classList.remove("task-card--working");',
  "    if (badge) badge.remove();",
  "  }",
  "}",
  "function persistMatrixWorking(card, working) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "PATCH",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ working: working, version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) setMatrixCardWorking(card, task.working === true, task.version);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function persistMatrixDelete(card) {",
  '  var taskId = card.getAttribute("data-task-id");',
  '  var version = card.getAttribute("data-version");',
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  '  fetch("/api/tasks/" + encodeURIComponent(taskId), {',
  '    method: "DELETE",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({ version: Number(version) }),',
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction();",
  '    if (typeof removeTaskDraft === "function") removeTaskDraft(taskId);',
  "    removeMatrixCard(card);",
  "    return null;",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function renderMatrixMenuItems(menu, card) {",
  "  var actions = [",
  '    { key: "delete", label: "delete" },',
  '    { key: "skip", label: "skip" },',
  '    { key: "done", label: "done" },',
  "  ];",
  '  var working = card && card.classList.contains("task-card--working");',
  '  actions.push({ key: "working", label: working ? "working: on" : "working: off" });',
  "  actions.forEach(function (action) {",
  '    var item = document.createElement("button");',
  '    item.type = "button";',
  '    item.className = "matrix-menu-item matrix-menu-item--" + action.key;',
  "    item.textContent = action.label;",
  '    item.setAttribute("data-matrix-action", action.key);',
  "    menu.appendChild(item);",
  "  });",
  "}",
  "var matrixModal = null;",
  "function closeMatrixModal() {",
  '  if (!matrixModal) return;',
  "  matrixModal.remove();",
  "  matrixModal = null;",
  "  matrixMenuCard = null;",
  "}",
  "function renderMatrixDeleteModal(card) {",
  '  var backdrop = document.createElement("div");',
  '  backdrop.className = "matrix-modal-backdrop";',
  '  var dialog = document.createElement("div");',
  '  dialog.className = "matrix-modal";',
  '  var message = document.createElement("p");',
  '  message.className = "matrix-modal-text";',
  '  message.textContent = "このタスクを削除しますか？";',
  "  dialog.appendChild(message);",
  '  var row = document.createElement("div");',
  '  row.className = "matrix-modal-actions";',
  '  var cancelButton = document.createElement("button");',
  '  cancelButton.type = "button";',
  '  cancelButton.className = "matrix-modal-button matrix-modal-button--cancel";',
  '  cancelButton.textContent = "キャンセル";',
  '  cancelButton.setAttribute("data-matrix-modal-action", "cancel");',
  "  row.appendChild(cancelButton);",
  '  var confirmButton = document.createElement("button");',
  '  confirmButton.type = "button";',
  '  confirmButton.className = "matrix-modal-button matrix-modal-button--danger";',
  '  confirmButton.textContent = "削除";',
  '  confirmButton.setAttribute("data-matrix-modal-action", "confirm");',
  "  row.appendChild(confirmButton);",
  "  dialog.appendChild(row);",
  '  backdrop.addEventListener("click", function (event) {',
  '    var button = event.target.closest ? event.target.closest("[data-matrix-modal-action]") : null;',
  "    if (!button) return;",
  '    var action = button.getAttribute("data-matrix-modal-action");',
  '    if (action === "confirm") { setTimeout(function () { closeMatrixModal(); persistMatrixDelete(card); }, 0); return; }',
  '    if (action === "cancel") { setTimeout(function () { closeMatrixModal(); }, 0); return; }',
  "  });",
  "  backdrop.appendChild(dialog);",
  "  document.body.appendChild(backdrop);",
  "  matrixModal = backdrop;",
  "}",
  "function openMatrixMenu(card, x, y) {",
  "  closeMatrixMenu();",
  "  matrixMenuCard = card;",
  '  var taskId = card.getAttribute("data-task-id") || "";',
  '  var menu = document.createElement("div");',
  '  menu.className = "matrix-menu";',
  "  renderMatrixMenuItems(menu, card);",
  '  menu.addEventListener("click", function (event) {',
  '    var item = event.target.closest("[data-matrix-action]");',
  "    if (!item) return;",
  '    var action = item.getAttribute("data-matrix-action");',
  '    if (action === "done" || action === "skip") { persistMatrixStatus(matrixMenuCard, action); return; }',
  '    if (action === "working") {',
  '      var workingCard = matrixMenuCard;',
  '      var working = workingCard && !workingCard.classList.contains("task-card--working");',
  "      persistMatrixWorking(workingCard, working);",
  "      return;",
  "    }",
  '    if (action === "delete") {',
  '      var card = matrixMenuCard;',
  '      setTimeout(function () { closeMatrixMenu(); renderMatrixDeleteModal(card); }, 0);',
  "      return;",
  "    }",
  "  });",
  "  document.body.appendChild(menu);",
  "  var rect = menu.getBoundingClientRect();",
  "  menu.style.left = Math.max(8, Math.min(x, window.innerWidth - rect.width - 8)) + 'px';",
  "  menu.style.top = Math.max(8, Math.min(y, window.innerHeight - rect.height - 8)) + 'px';",
  "  matrixMenu = menu;",
  "  matrixMenuJustOpened = true;",
  "  void taskId;",
  "}",
  'document.addEventListener("contextmenu", function (event) {',
  '  var card = event.target.closest ? event.target.closest(".matrix-cards .task-card") : null;',
  "  if (!card || matrixActionPending) return;",
  "  event.preventDefault();",
  "  openMatrixMenu(card, event.clientX, event.clientY);",
  "});",
  'document.addEventListener("click", function (event) {',
  "  if (!matrixMenu) return;",
  "  if (matrixMenu.contains(event.target)) { matrixMenuJustOpened = false; return; }",
  "  if (matrixMenuJustOpened) { matrixMenuJustOpened = false; return; }",
  "  closeMatrixMenu();",
  "}, true);",
].join("\n");

export const IDEAS_DND_SCRIPT = [
  "var ideasDraggingCard = null;",
  "function ideasCardFromEvent(event) {",
  '  var target = event.target;',
  '  return target && target.closest ? target.closest(".ideas-grid > .idea-card") : null;',
  "}",
  "function ideasSameGroup(left, right) {",
  '  return left && right && left.getAttribute("data-pinned") === right.getAttribute("data-pinned");',
  "}",
  "function clearIdeasDrag() {",
  '  if (ideasDraggingCard) ideasDraggingCard.classList.remove("dragging");',
  '  document.querySelectorAll(".ideas-grid .drop-target").forEach(function (card) { card.classList.remove("drop-target"); });',
  "  ideasDraggingCard = null;",
  "}",
  'document.addEventListener("dragstart", function (event) {',
  "  var card = ideasCardFromEvent(event);",
  "  if (!card || !event.dataTransfer) return;",
  "  ideasDraggingCard = card;",
  '  card.classList.add("dragging");',
  '  event.dataTransfer.effectAllowed = "move";',
  '  event.dataTransfer.setData("text/plain", card.getAttribute("data-order") || "");',
  "});",
  'document.addEventListener("dragover", function (event) {',
  "  if (!ideasDraggingCard || !event.dataTransfer) return;",
  "  var target = ideasCardFromEvent(event);",
  "  if (!target || target === ideasDraggingCard || !ideasSameGroup(ideasDraggingCard, target)) return;",
  "  event.preventDefault();",
  '  event.dataTransfer.dropEffect = "move";',
  '  document.querySelectorAll(".ideas-grid .drop-target").forEach(function (card) { card.classList.remove("drop-target"); });',
  '  target.classList.add("drop-target");',
  "  var box = target.getBoundingClientRect();",
  "  if (event.clientY < box.top + box.height / 2) target.before(ideasDraggingCard);",
  "  else target.after(ideasDraggingCard);",
  '  if (typeof layoutIdeaMasonry === "function") layoutIdeaMasonry();',
  "});",
  'document.addEventListener("drop", function (event) {',
  "  if (!ideasDraggingCard) return;",
  "  var target = ideasCardFromEvent(event);",
  "  if (target && ideasSameGroup(ideasDraggingCard, target)) event.preventDefault();",
  "});",
  'document.addEventListener("dragend", clearIdeasDrag);',
  'document.addEventListener("DOMContentLoaded", clearIdeasDrag);',
  'document.addEventListener("htmx:load", clearIdeasDrag);',
].join("\n");

export const IDEA_DETAIL_SCRIPT = [
  "function ideaDraftKey(form) {",
  '  var order = form.getAttribute("data-idea-order");',
  '  return order ? "siftq.idea-draft:" + order : null;',
  "}",
  "function readCreatedIdeas() {",
  '  try {',
  '    var raw = localStorage.getItem("siftq.idea-created");',
  '    var ideas = raw ? JSON.parse(raw) : [];',
  '    return Array.isArray(ideas) ? ideas.filter(function (idea) { return idea && typeof idea.order === "string" && typeof idea.title === "string" && typeof idea.description === "string" && typeof idea.pinned === "boolean"; }) : [];',
  '  } catch (error) { return []; }',
  "}",
  "function writeCreatedIdeas(ideas) {",
  '  try { localStorage.setItem("siftq.idea-created", JSON.stringify(ideas)); } catch (error) {}',
  "}",
  "function readDeletedIdeas() {",
  '  try {',
  '    var raw = localStorage.getItem("siftq.idea-deleted");',
  '    var orders = raw ? JSON.parse(raw) : [];',
  '    return Array.isArray(orders) ? orders.filter(function (order) { return typeof order === "string"; }) : [];',
  '  } catch (error) { return []; }',
  "}",
  "function writeDeletedIdeas(orders) {",
  '  try { localStorage.setItem("siftq.idea-deleted", JSON.stringify(orders)); } catch (error) {}',
  "}",
  "function isIdeaDeleted(order) {",
  '  return readDeletedIdeas().indexOf(order) !== -1;',
  "}",
  "function readIdeaDraft(form) {",
  "  var key = ideaDraftKey(form);",
  "  if (!key) return null;",
  "  try {",
  "    var raw = localStorage.getItem(key);",
  "    if (!raw) return null;",
  "    var draft = JSON.parse(raw);",
  '    return draft && typeof draft.title === "string" && typeof draft.description === "string" && (draft.pinned === undefined || typeof draft.pinned === "boolean") ? draft : null;',
  "  } catch (error) { return null; }",
  "}",
  "function ideaDraftFields(form) {",
  '  return { title: form.querySelector(\'input[name="title"]\'), description: form.querySelector(\'textarea[name="description"]\') };',
  "}",
  "function ideaFormPinned(form) {",
  '  return form.getAttribute("data-idea-pinned") === "true";',
  "}",
  "function updateIdeaPinButton(form) {",
  '  var button = form.querySelector("[data-idea-pin]");',
  "  if (!button) return;",
  '  button.setAttribute("aria-pressed", ideaFormPinned(form) ? "true" : "false");',
  '  button.setAttribute("aria-label", ideaFormPinned(form) ? "Unpin idea" : "Pin idea");',
  "}",
  "function resizeIdeaDescription(form) {",
  '  var description = form.querySelector(".idea-detail__description");',
  "  if (!description) return;",
  '  description.style.height = "auto";',
  '  description.style.height = description.scrollHeight + "px";',
  "}",
  "function resizeIdeaComposer(composer) {",
  '  var description = composer.querySelector(".ideas-composer__description");',
  "  if (!description) return;",
  '  description.style.height = "auto";',
  '  description.style.height = Math.min(description.scrollHeight, 320) + "px";',
  "}",
  "function setIdeaComposerOpen(composer, open) {",
  '  var trigger = composer.querySelector("[data-idea-composer-trigger]");',
  '  var editor = composer.querySelector("[data-idea-composer-editor]");',
  '  composer.classList.toggle("ideas-composer--open", open);',
  '  composer.setAttribute("data-idea-composer-open", open ? "true" : "false");',
  '  if (trigger) trigger.setAttribute("aria-expanded", open ? "true" : "false");',
  '  if (editor) editor.hidden = !open;',
  '  if (open) { resizeIdeaComposer(composer); var title = composer.querySelector(".ideas-composer__title"); if (title) title.focus(); }',
  "}",
  "function finishIdeaComposer(composer) {",
  '  var title = composer.querySelector(".ideas-composer__title");',
  '  var description = composer.querySelector(".ideas-composer__description");',
  '  createNewIdea(title ? title.value.trim() : "", description ? description.value.trim() : "");',
  '  if (title) title.value = "";',
  '  if (description) description.value = "";',
  '  setIdeaComposerOpen(composer, false);',
  "}",
  "function restoreIdeaDraft(form) {",
  "  var draft = readIdeaDraft(form);",
  "  if (!draft) return;",
  "  var fields = ideaDraftFields(form);",
  "  if (fields.title) fields.title.value = draft.title;",
  "  if (fields.description) fields.description.value = draft.description;",
  '  if (typeof draft.pinned === "boolean") form.setAttribute("data-idea-pinned", draft.pinned ? "true" : "false");',
  "  updateIdeaPinButton(form);",
  "  resizeIdeaDescription(form);",
  "}",
  "function saveIdeaDraft(form) {",
  "  var key = ideaDraftKey(form);",
  "  if (!key) return;",
  "  var fields = ideaDraftFields(form);",
  "  var draft = { title: fields.title ? fields.title.value : \"\", description: fields.description ? fields.description.value : \"\", pinned: ideaFormPinned(form), updatedAt: Date.now() };",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (error) {}",
  "  syncIdeaCard(form);",
  "}",
  "function createIdeaPin(pinned) {",
  '  var pin = document.createElementNS("http://www.w3.org/2000/svg", "svg");',
  '  pin.setAttribute("class", "idea-card__pin");',
  '  pin.setAttribute("role", "img");',
  '  pin.setAttribute("aria-label", pinned ? "Pinned" : "Not pinned");',
  '  pin.setAttribute("viewBox", "0 0 24 24");',
  '  var path = document.createElementNS("http://www.w3.org/2000/svg", "path");',
  '  path.setAttribute("d", "M16 12V4h1V2H7v2h1v8l-2 2v2h5.8v6h2.4v-6H20v-2z");',
  '  pin.appendChild(path);',
  '  return pin;',
  "}",
  "function updateIdeaCardPin(card, pinned) {",
  '  card.setAttribute("data-pinned", pinned ? "true" : "false");',
  '  var link = card.querySelector(".idea-card__link");',
  '  var pin = card.querySelector(".idea-card__pin");',
  '  if (pinned && !pin && link) {',
  '    pin = createIdeaPin(pinned);',
  '    link.prepend(pin);',
  "  }",
  '  if (pin) pin.setAttribute("aria-label", pinned ? "Pinned" : "Not pinned");',
  "}",
  "function layoutIdeaMasonryGrid(grid) {",
  '  var cards = Array.prototype.slice.call(grid.querySelectorAll(":scope > .idea-card"));',
  '  grid.classList.remove("masonry-ready");',
  '  grid.style.height = "";',
  '  cards.forEach(function (card) { card.style.left = ""; card.style.top = ""; card.style.width = ""; });',
  "  if (cards.length === 0) return;",
  '  var columns = getComputedStyle(grid).gridTemplateColumns.trim().split(/\\s+/).length;',
  '  var gap = 16;',
  '  var columnWidth = (grid.clientWidth - gap * (columns - 1)) / columns;',
  '  cards.forEach(function (card) { card.style.width = columnWidth + "px"; });',
  '  grid.classList.add("masonry-ready");',
  '  var heights = Array(columns).fill(0);',
  '  cards.forEach(function (card) {',
  '    var column = heights.indexOf(Math.min.apply(null, heights));',
  '    card.style.left = (column * (columnWidth + gap)) + "px";',
  '    card.style.top = heights[column] + "px";',
  '    heights[column] += card.offsetHeight + gap;',
  "  });",
  '  grid.style.height = Math.max.apply(null, heights) - gap + "px";',
  "}",
  "function layoutIdeaMasonry() {",
  '  document.querySelectorAll(".ideas-grid").forEach(layoutIdeaMasonryGrid);',
  "}",
  "function updateIdeaGroups() {",
  '  var pinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="pinned"]`);',
  '  var unpinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="unpinned"]`);',
  "  if (!pinnedGrid || !unpinnedGrid) return;",
  '  var cards = Array.prototype.slice.call(document.querySelectorAll(".ideas-grid > .idea-card"));',
  '  var pinned = cards.filter(function (card) { return card.getAttribute("data-pinned") === "true"; });',
  '  var unpinned = cards.filter(function (card) { return card.getAttribute("data-pinned") !== "true"; });',
  '  var empty = document.querySelector("[data-ideas-empty]");',
  '  if (empty) empty.hidden = cards.length > 0;',
  '  pinned.forEach(function (card) { pinnedGrid.appendChild(card); });',
  '  unpinned.forEach(function (card) { unpinnedGrid.appendChild(card); });',
  '  var gap = document.querySelector("[data-idea-group-gap]");',
  '  if (gap) gap.hidden = pinned.length === 0 || unpinned.length === 0;',
  '  layoutIdeaMasonry();',
  "}",
  "function createIdeaCard(idea) {",
  '  var card = document.createElement("article");',
  '  card.className = "idea-card";',
  '  card.setAttribute("data-idea-order", idea.order);',
  '  card.setAttribute("data-order", idea.order);',
  '  card.setAttribute("data-pinned", idea.pinned ? "true" : "false");',
  '  card.setAttribute("draggable", "true");',
  '  var link = document.createElement("a");',
  '  link.className = "idea-card__link";',
  '  link.href = "/ideas/" + encodeURIComponent(idea.order);',
  '  link.appendChild(createIdeaPin(idea.pinned));',
  '  var title = document.createElement("h2");',
  '  title.textContent = idea.title;',
  '  link.appendChild(title);',
  '  var description = document.createElement("p");',
  '  description.className = idea.description ? "idea-card__description" : "idea-card__description idea-card__description--empty";',
  '  description.textContent = idea.description || "No description yet.";',
  '  link.appendChild(description);',
  '  card.appendChild(link);',
  '  var footer = document.createElement("footer");',
  '  footer.className = "idea-card__footer";',
  '  var more = document.createElement("button");',
  '  more.type = "button";',
  '  more.className = "idea-card__more";',
  '  more.setAttribute("aria-label", "More options for " + idea.title);',
  '  var dots = document.createElement("span");',
  '  dots.setAttribute("aria-hidden", "true");',
  '  more.appendChild(dots);',
  '  footer.appendChild(more);',
  '  card.appendChild(footer);',
  '  return card;',
  "}",
  "function restoreCreatedIdeas() {",
  '  var pinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="pinned"]`);',
  '  var unpinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="unpinned"]`);',
  '  if (!pinnedGrid || !unpinnedGrid) return;',
  '  readCreatedIdeas().forEach(function (idea) {',
  '    if (isIdeaDeleted(idea.order)) return;',
  '    if (document.querySelector(`.idea-card[data-idea-order="${idea.order}"]`)) return;',
  '    (idea.pinned ? pinnedGrid : unpinnedGrid).appendChild(createIdeaCard(idea));',
  '  });',
  "}",
  "function restoreDeletedIdeas() {",
  '  document.querySelectorAll(".idea-card[data-idea-order]").forEach(function (card) {',
  '    var order = card.getAttribute("data-idea-order");',
  '    if (order && isIdeaDeleted(order)) card.remove();',
  '  });',
  "}",
  "function removeIdeaCard(card) {",
  '  var order = card.getAttribute("data-idea-order");',
  '  if (!order) return;',
  '  writeCreatedIdeas(readCreatedIdeas().filter(function (idea) { return idea.order !== order; }));',
  '  if (order.indexOf("created-") !== 0) {',
  '    var deleted = readDeletedIdeas();',
  '    if (deleted.indexOf(order) === -1) { deleted.push(order); writeDeletedIdeas(deleted); }',
  '  }',
  '  try { localStorage.removeItem("siftq.idea-draft:" + order); } catch (error) {}',
  '  card.remove();',
  '  updateIdeaGroups();',
  "}",
  "var ideaMenu = null;",
  "var ideaMenuCard = null;",
  "var ideaDeleteModal = null;",
  "function closeIdeaMenu() {",
  '  if (ideaMenu) ideaMenu.remove();',
  '  ideaMenu = null;',
  '  ideaMenuCard = null;',
  "}",
  "function closeIdeaDeleteModal() {",
  '  if (ideaDeleteModal) ideaDeleteModal.remove();',
  '  ideaDeleteModal = null;',
  "}",
  "function renderIdeaDeleteModal(card) {",
  '  var backdrop = document.createElement("div");',
  '  backdrop.className = "matrix-modal-backdrop";',
  '  var dialog = document.createElement("div");',
  '  dialog.className = "matrix-modal";',
  '  var message = document.createElement("p");',
  '  message.className = "matrix-modal-text";',
  '  message.textContent = "このメモを削除しますか？";',
  '  dialog.appendChild(message);',
  '  var row = document.createElement("div");',
  '  row.className = "matrix-modal-actions";',
  '  var cancelButton = document.createElement("button");',
  '  cancelButton.type = "button";',
  '  cancelButton.className = "matrix-modal-button matrix-modal-button--cancel";',
  '  cancelButton.textContent = "キャンセル";',
  '  cancelButton.setAttribute("data-idea-modal-action", "cancel");',
  '  row.appendChild(cancelButton);',
  '  var confirmButton = document.createElement("button");',
  '  confirmButton.type = "button";',
  '  confirmButton.className = "matrix-modal-button matrix-modal-button--danger";',
  '  confirmButton.textContent = "削除";',
  '  confirmButton.setAttribute("data-idea-modal-action", "confirm");',
  '  row.appendChild(confirmButton);',
  '  dialog.appendChild(row);',
  '  backdrop.addEventListener("click", function (event) {',
  '    var button = event.target.closest ? event.target.closest("[data-idea-modal-action]") : null;',
  '    if (!button) return;',
  '    var action = button.getAttribute("data-idea-modal-action");',
  '    if (action === "confirm") { setTimeout(function () { closeIdeaDeleteModal(); removeIdeaCard(card); }, 0); return; }',
  '    if (action === "cancel") { setTimeout(function () { closeIdeaDeleteModal(); }, 0); return; }',
  '  });',
  '  backdrop.appendChild(dialog);',
  '  document.body.appendChild(backdrop);',
  '  ideaDeleteModal = backdrop;',
  "}",
  "function openIdeaMenu(card, button) {",
  '  closeIdeaMenu();',
  '  ideaMenuCard = card;',
  '  var menu = document.createElement("div");',
  '  menu.className = "matrix-menu";',
  '  var deleteButton = document.createElement("button");',
  '  deleteButton.type = "button";',
  '  deleteButton.className = "matrix-menu-item matrix-menu-item--delete";',
  '  deleteButton.textContent = "削除";',
  '  deleteButton.setAttribute("data-idea-action", "delete");',
  '  menu.appendChild(deleteButton);',
  '  menu.addEventListener("click", function (event) {',
  '    var item = event.target.closest("[data-idea-action]");',
  '    if (!item) return;',
  '    if (item.getAttribute("data-idea-action") === "delete") { var target = ideaMenuCard; closeIdeaMenu(); renderIdeaDeleteModal(target); }',
  '  });',
  '  document.body.appendChild(menu);',
  '  var rect = button.getBoundingClientRect();',
  '  var menuRect = menu.getBoundingClientRect();',
  '  menu.style.left = Math.max(8, Math.min(rect.left, window.innerWidth - menuRect.width - 8)) + "px";',
  '  menu.style.top = Math.max(8, Math.min(rect.bottom + 4, window.innerHeight - menuRect.height - 8)) + "px";',
  '  ideaMenu = menu;',
  "}",
  "function syncIdeaCard(form) {",
  '  var order = form.getAttribute("data-idea-order");',
  '  var card = order ? document.querySelector(`.idea-card[data-idea-order="${order}"]`) : null;',
  "  if (!card) return;",
  '  var fields = ideaDraftFields(form);',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  if (title && fields.title) title.textContent = fields.title.value;',
  '  if (description && fields.description) description.textContent = fields.description.value || "No description yet.";',
  '  if (description) description.classList.toggle("idea-card__description--empty", !fields.description || !fields.description.value);',
  '  updateIdeaCardPin(card, ideaFormPinned(form));',
  "  updateIdeaGroups();",
  "}",
  "function setIdeaPinned(form, pinned) {",
  '  form.setAttribute("data-idea-pinned", pinned ? "true" : "false");',
  "  updateIdeaPinButton(form);",
  "  saveIdeaDraft(form);",
  "}",
  "function toggleIdeaCardPin(card) {",
  '  var order = card.getAttribute("data-idea-order");',
  '  if (!order) return;',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  var pinned = card.getAttribute("data-pinned") !== "true";',
  '  var draft = { title: title ? title.textContent || "" : "", description: description ? description.textContent || "" : "", pinned: pinned, updatedAt: Date.now() };',
  '  try { localStorage.setItem("siftq.idea-draft:" + order, JSON.stringify(draft)); } catch (error) {}',
  '  updateIdeaCardPin(card, pinned);',
  "  updateIdeaGroups();",
  "}",
  "function scheduleIdeaDraftSave(form) {",
  '  if (form._ideaDraftTimer) clearTimeout(form._ideaDraftTimer);',
  "  form._ideaDraftTimer = setTimeout(function () { saveIdeaDraft(form); }, 400);",
  "}",
  "function restoreIdeaCardDrafts() {",
  '  document.querySelectorAll(".idea-card[data-idea-order]").forEach(function (card) {',
  '    var order = card.getAttribute("data-idea-order");',
  '    if (!order) return;',
  '    var raw;',
  '    try { raw = localStorage.getItem("siftq.idea-draft:" + order); } catch (error) { return; }',
  '    if (!raw) return;',
  '    var draft;',
  '    try { draft = JSON.parse(raw); } catch (error) { return; }',
  '    if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  '    var title = card.querySelector("h2");',
  '    var description = card.querySelector(".idea-card__description");',
  '    if (title) title.textContent = draft.title;',
  '    if (description) description.textContent = draft.description || "No description yet.";',
  '    if (typeof draft.pinned === "boolean") updateIdeaCardPin(card, draft.pinned);',
  "  });",
  "  updateIdeaGroups();",
  "}",
  "function createNewIdea(title, description) {",
  '  if (!title && !description) return;',
  '  var idea = { order: "created-" + Date.now() + "-" + Math.random().toString(36).slice(2, 8), title: title || "無題", description: description, pinned: false };',
  '  var ideas = readCreatedIdeas();',
  '  ideas.push(idea);',
  '  writeCreatedIdeas(ideas);',
  '  var grid = document.querySelector(`.ideas-grid[data-idea-group="${idea.pinned ? "pinned" : "unpinned"}"]`);',
  '  if (grid) grid.appendChild(createIdeaCard(idea));',
  '  updateIdeaGroups();',
  "}",
  "function initializeIdeaComposer() {",
  '  document.querySelectorAll("[data-idea-composer]").forEach(function (composer) {',
  '    if (composer.dataset.ideaComposerInitialized === "true") return;',
  '    composer.dataset.ideaComposerInitialized = "true";',
  '    setIdeaComposerOpen(composer, false);',
  '    var trigger = composer.querySelector("[data-idea-composer-trigger]");',
  '    var close = composer.querySelector("[data-idea-composer-close]");',
  '    var description = composer.querySelector(".ideas-composer__description");',
  '    if (trigger) trigger.addEventListener("click", function () { setIdeaComposerOpen(composer, true); });',
  '    if (close) close.addEventListener("click", function () { finishIdeaComposer(composer); });',
  '    if (description) description.addEventListener("input", function () { resizeIdeaComposer(composer); });',
  '    document.addEventListener("click", function (event) {',
  '      if (composer.getAttribute("data-idea-composer-open") !== "true" || event.target.closest("[data-idea-composer]")) return;',
  '      finishIdeaComposer(composer);',
  '    });',
  "  });",
  "}",
  "function openIdeaModal(card) {",
  '  var modal = document.querySelector("[data-idea-modal]");',
  '  var form = modal ? modal.querySelector("form[data-idea-form]") : null;',
  "  if (!modal || !form) return;",
  '  var order = card.getAttribute("data-idea-order");',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  form.setAttribute("data-idea-order", order || "");',
  '  form.setAttribute("data-idea-mode", "edit");',
  '  form.setAttribute("data-idea-pinned", card.getAttribute("data-pinned") === "true" ? "true" : "false");',
  "  var fields = ideaDraftFields(form);",
  '  if (fields.title) fields.title.value = title ? title.textContent || "" : "";',
  '  if (fields.description) fields.description.value = description ? description.textContent || "" : "";',
  "  updateIdeaPinButton(form);",
  "  resizeIdeaDescription(form);",
  "  restoreIdeaDraft(form);",
  '  var close = modal.querySelector("[data-idea-close]");',
  '  if (close) close.textContent = "閉じる";',
  '  if (typeof modal.showModal === "function" && !modal.open) modal.showModal();',
  "  resizeIdeaDescription(form);",
  "}",
  "function initializeIdeaDetails() {",
  "  initializeIdeaComposer();",
  "  restoreDeletedIdeas();",
  "  restoreCreatedIdeas();",
  "  restoreIdeaCardDrafts();",
  '  document.querySelectorAll("form[data-idea-form]").forEach(function (form) {',
  '    if (form.dataset.ideaDetailInitialized === "true") return;',
  '    form.dataset.ideaDetailInitialized = "true";',
  "    restoreIdeaDraft(form);",
  '    updateIdeaPinButton(form);',
  '    resizeIdeaDescription(form);',
  '    form.addEventListener("input", function () { resizeIdeaDescription(form); scheduleIdeaDraftSave(form); });',
  '    var pin = form.querySelector("[data-idea-pin]");',
  '    if (pin) pin.addEventListener("click", function () { setIdeaPinned(form, !ideaFormPinned(form)); });',
  "  });",
  '  document.querySelectorAll("[data-idea-modal]").forEach(function (modal) {',
  '    if (modal.dataset.ideaModalInitialized === "true") return;',
  '    modal.dataset.ideaModalInitialized = "true";',
  '    var close = modal.querySelector("[data-idea-close]");',
   '    if (close) close.addEventListener("click", function () { modal.close(); });',
  '    document.addEventListener("click", function (event) {',
  '      if (!modal.open) return;',
   '      if (event.target.closest(".idea-card") || event.target.closest(".ideas-composer")) return;',
  '      var box = modal.getBoundingClientRect();',
  '      var outside = event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom;',
    '      if (outside || event.target === modal) modal.close();',
  '    });',
  "  });",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeIdeaDetails);',
  'document.addEventListener("htmx:load", initializeIdeaDetails);',
  'window.addEventListener("resize", layoutIdeaMasonry);',
  'document.addEventListener("click", function (event) {',
  '  if (!ideaMenu || ideaMenu.contains(event.target)) return;',
  '  closeIdeaMenu();',
  '}, true);',
    'document.addEventListener("click", function (event) {',
    '  var modal = document.querySelector("[data-idea-modal]");',
    '  if (modal && modal.open) return;',
    '  if (document.querySelector(`[data-idea-composer][data-idea-composer-open="true"]`)) return;',
   '  var card = event.target.closest(".idea-card[data-idea-order]");',
   '  var order = card ? card.getAttribute("data-idea-order") : null;',
   '  if (!card || !order) return;',
   '  var more = event.target.closest(".idea-card__more");',
   '  if (more) { event.preventDefault(); openIdeaMenu(card, more); return; }',
  '  if (event.target.closest(".idea-card__pin")) { event.preventDefault(); toggleIdeaCardPin(card); return; }',
  '  event.preventDefault();',
  '  openIdeaModal(card);',
  "});",
].join("\n");
