export const HTMX_CONFLICT_SWAP_SCRIPT = [
  "document.body.addEventListener('htmx:beforeSwap', function (event) {",
  "  if (event.detail.xhr.status !== 409) return;",
  "  event.detail.shouldSwap = true;",
  "  event.detail.isError = false;",
  "});",
].join("\n");

export const POPOVER_DISMISS_SCRIPT = [
  "document.addEventListener('click', function (event) {",
  "  const target = event.target;",
  "  const cancel = target && target.closest ? target.closest('[data-popover-cancel]') : null;",
  "  Array.prototype.forEach.call(document.querySelectorAll('[data-popover-close][open]'), function (details) {",
  "    if (cancel ? details.contains(cancel) : !details.contains(target)) details.removeAttribute('open');",
  "  });",
  "  const panel = document.querySelector('[data-popover-close-href]');",
  "  if (!panel || panel.contains(event.target)) return;",
  "  const href = panel.getAttribute('data-popover-close-href');",
  "  if (href) window.location.assign(href);",
  "});",
  "document.addEventListener('change', function (event) {",
  "  const target = event.target;",
  "  const details = target && target.closest ? target.closest('[data-popover-close]') : null;",
  "  if (details) details.removeAttribute('open');",
  "});",
].join("\n");

export const TASK_FORM_SHORTCUT_SCRIPT = [
  "document.addEventListener(\"keydown\", function (event) {",
  "  if (!event.ctrlKey || event.key !== \"Enter\") return;",
  "  const target = event.target;",
  "  const editor = target && target.closest ? target.closest(\"[data-description-editor]\") : null;",
  "  const isDescriptionEditor = Boolean(editor);",
  "  if (!target || (!isDescriptionEditor && target.name !== \"title\" && target.name !== \"description\")) return;",
  "  const form = target.closest ? target.closest(\"form[data-task-form]\") : null;",
  "  if (!form) return;",
  "  event.preventDefault();",
  "  if (form.dataset.shortcutSubmitting === \"true\") return;",
  "  if (!form.checkValidity()) { form.reportValidity(); return; }",
  "  form.dataset.shortcutSubmitting = \"true\";",
  "  form.requestSubmit();",
  "});",
  "window.addEventListener(\"pageshow\", function (event) {",
  "  if (!event.persisted) return;",
  "  if (!document.querySelector('form[data-task-form=\"edit\"]')) return;",
  "  window.location.reload();",
  "});",
].join("\n");

/* Legacy Idea localStorage scripts were replaced by src/client/idea-scripts.ts.
   Keep this block out of the Worker bundle until the old source is removed. */
/*
export const IDEAS_DND_SCRIPT = [
  "var ideasDraggingCard = null;",
  "function ideasCardFromEvent(event) {",
  '  var target = event.target;',
  '  return target && target.closest ? target.closest(".ideas-grid > .idea-card") : null;',
  "}",
  "function ideasSameGroup(left, right) {",
  '  return left && right && left.getAttribute("data-pinned") === right.getAttribute("data-pinned");',
  "}",
  "function clearIdeasDrag() {",
  '  if (ideasDraggingCard) ideasDraggingCard.classList.remove("dragging");',
  '  document.querySelectorAll(".ideas-grid .drop-target").forEach(function (card) { card.classList.remove("drop-target"); });',
  "  ideasDraggingCard = null;",
  "}",
  'document.addEventListener("dragstart", function (event) {',
  "  var card = ideasCardFromEvent(event);",
  "  if (!card || !event.dataTransfer) return;",
  "  ideasDraggingCard = card;",
  '  card.classList.add("dragging");',
  '  event.dataTransfer.effectAllowed = "move";',
  '  event.dataTransfer.setData("text/plain", card.getAttribute("data-order") || "");',
  "});",
  'document.addEventListener("dragover", function (event) {',
  "  if (!ideasDraggingCard || !event.dataTransfer) return;",
  "  var target = ideasCardFromEvent(event);",
  "  if (!target || target === ideasDraggingCard || !ideasSameGroup(ideasDraggingCard, target)) return;",
  "  event.preventDefault();",
  '  event.dataTransfer.dropEffect = "move";',
  '  document.querySelectorAll(".ideas-grid .drop-target").forEach(function (card) { card.classList.remove("drop-target"); });',
  '  target.classList.add("drop-target");',
  "  var box = target.getBoundingClientRect();",
  "  if (event.clientY < box.top + box.height / 2) target.before(ideasDraggingCard);",
  "  else target.after(ideasDraggingCard);",
  '  if (typeof layoutIdeaMasonry === "function") layoutIdeaMasonry();',
  "});",
  'document.addEventListener("drop", function (event) {',
  "  if (!ideasDraggingCard) return;",
  "  var target = ideasCardFromEvent(event);",
  "  if (target && ideasSameGroup(ideasDraggingCard, target)) { event.preventDefault(); normalizeIdeaGroupOrder(ideasDraggingCard.parentElement); persistIdeaOrders(); }",
  "});",
  'document.addEventListener("dragend", clearIdeasDrag);',
  'document.addEventListener("DOMContentLoaded", clearIdeasDrag);',
  'document.addEventListener("htmx:load", clearIdeasDrag);',
].join("\n");
export const IDEA_DETAIL_SCRIPT = [
  "function ideaDraftKey(form) {",
  '  var id = form.getAttribute("data-idea-id");',
  '  return id ? "siftq.idea-draft:" + id : null;',
  "}",
  "function ideaCardId(card) {",
  '  return card.getAttribute("data-idea-id") || card.getAttribute("data-idea-order");',
  "}",
  "function ideaCardOrder(card) {",
  '  var order = Number(card.getAttribute("data-idea-order"));',
  '  return Number.isFinite(order) ? order : 0;',
  "}",
  "function setIdeaCardOrder(card, order) {",
  '  card.setAttribute("data-idea-order", String(order));',
  '  card.setAttribute("data-order", String(order));',
  "}",
  "function readCreatedIdeas() {",
  '  try {',
  '    var raw = localStorage.getItem("siftq.idea-created");',
  '    var ideas = raw ? JSON.parse(raw) : [];',
  '    if (!Array.isArray(ideas)) return [];',
  '    return ideas.flatMap(function (idea) {',
  '      if (!idea || typeof idea.title !== "string" || typeof idea.description !== "string" || typeof idea.pinned !== "boolean") return [];',
  '      if (typeof idea.id === "string" && typeof idea.order === "number" && Number.isFinite(idea.order)) return [idea];',
  '      if (typeof idea.order === "string") return [{ id: idea.order, order: 0, title: idea.title, description: idea.description, pinned: idea.pinned }];',
  '      return [];',
  '    });',
  '  } catch (error) { return []; }',
  "}",
  "function writeCreatedIdeas(ideas) {",
  '  try { localStorage.setItem("siftq.idea-created", JSON.stringify(ideas)); } catch (error) {}',
  "}",
  "function readDeletedIdeas() {",
  '  try {',
  '    var raw = localStorage.getItem("siftq.idea-deleted");',
  '    var orders = raw ? JSON.parse(raw) : [];',
  '    return Array.isArray(orders) ? orders.filter(function (order) { return typeof order === "string"; }) : [];',
  '  } catch (error) { return []; }',
  "}",
  "function writeDeletedIdeas(orders) {",
  '  try { localStorage.setItem("siftq.idea-deleted", JSON.stringify(orders)); } catch (error) {}',
  "}",
  "function isIdeaDeleted(id) {",
  '  return readDeletedIdeas().indexOf(id) !== -1;',
  "}",
  "function readIdeaOrders() {",
  '  try {',
  '    var raw = localStorage.getItem("siftq.idea-order");',
  '    var orders = raw ? JSON.parse(raw) : {};',
  '    if (!orders || typeof orders !== "object" || Array.isArray(orders)) return {};',
  '    Object.keys(orders).forEach(function (id) { if (typeof orders[id] !== "number" || !Number.isFinite(orders[id])) delete orders[id]; });',
  '    return orders;',
  '  } catch (error) { return {}; }',
  "}",
  "function writeIdeaOrders(orders) {",
  '  try { localStorage.setItem("siftq.idea-order", JSON.stringify(orders)); } catch (error) {}',
  "}",
  "function ideaCardById(id) {",
  '  var card = null;',
  '  document.querySelectorAll(".idea-card[data-idea-id]").forEach(function (candidate) { if (card === null && ideaCardId(candidate) === id) card = candidate; });',
  '  return card;',
  "}",
  "function persistIdeaOrders() {",
  '  var overrides = {};',
  '  var created = readCreatedIdeas();',
  '  document.querySelectorAll(".idea-card[data-idea-id]").forEach(function (card) {',
  '    var id = ideaCardId(card);',
  '    var order = ideaCardOrder(card);',
  '    if (!id) return;',
  '    if (id.indexOf("created-") === 0) {',
  '      created.forEach(function (idea) { if (idea.id === id) idea.order = order; });',
  '    } else { overrides[id] = order; }',
  '  });',
  '  writeIdeaOrders(overrides);',
  '  writeCreatedIdeas(created);',
  "}",
  "function restoreIdeaOrders() {",
  '  var overrides = readIdeaOrders();',
  '  document.querySelectorAll(".idea-card[data-idea-id]").forEach(function (card) {',
  '    var id = ideaCardId(card);',
  '    if (id && typeof overrides[id] === "number") setIdeaCardOrder(card, overrides[id]);',
  '  });',
  "}",
  "function readIdeaDraft(form) {",
  "  var key = ideaDraftKey(form);",
  "  if (!key) return null;",
  "  try {",
  "    var raw = localStorage.getItem(key);",
  "    if (!raw) return null;",
  "    var draft = JSON.parse(raw);",
  '    return draft && typeof draft.title === "string" && typeof draft.description === "string" && (draft.pinned === undefined || typeof draft.pinned === "boolean") && (draft.order === undefined || (typeof draft.order === "number" && Number.isFinite(draft.order))) ? draft : null;',
  "  } catch (error) { return null; }",
  "}",
  "function ideaDraftFields(form) {",
  '  return { title: form.querySelector(\'input[name="title"]\'), description: form.querySelector(\'textarea[name="description"]\') };',
  "}",
  "function ideaFormPinned(form) {",
  '  return form.getAttribute("data-idea-pinned") === "true";',
  "}",
  "function updateIdeaPinButton(form) {",
  '  var button = form.querySelector("[data-idea-pin]");',
  "  if (!button) return;",
  '  button.setAttribute("aria-pressed", ideaFormPinned(form) ? "true" : "false");',
  '  button.setAttribute("aria-label", ideaFormPinned(form) ? "Unpin idea" : "Pin idea");',
  "}",
  "function resizeIdeaDescription(form) {",
  '  var description = form.querySelector(".idea-detail__description");',
  "  if (!description) return;",
  '  description.style.height = "auto";',
  '  description.style.height = description.scrollHeight + "px";',
  "}",
  "function resizeIdeaComposer(composer) {",
  '  var description = composer.querySelector(".ideas-composer__description");',
  "  if (!description) return;",
  '  description.style.height = "auto";',
  '  description.style.height = Math.min(description.scrollHeight, 320) + "px";',
  "}",
  "function setIdeaComposerOpen(composer, open) {",
  '  var trigger = composer.querySelector("[data-idea-composer-trigger]");',
  '  var editor = composer.querySelector("[data-idea-composer-editor]");',
  '  composer.classList.toggle("ideas-composer--open", open);',
  '  composer.setAttribute("data-idea-composer-open", open ? "true" : "false");',
  '  if (trigger) trigger.setAttribute("aria-expanded", open ? "true" : "false");',
  '  if (editor) editor.hidden = !open;',
  '  if (open) { resizeIdeaComposer(composer); var title = composer.querySelector(".ideas-composer__title"); if (title) title.focus(); }',
  "}",
  "function finishIdeaComposer(composer) {",
  '  var title = composer.querySelector(".ideas-composer__title");',
  '  var description = composer.querySelector(".ideas-composer__description");',
  '  createNewIdea(title ? title.value.trim() : "", description ? description.value.trim() : "");',
  '  if (title) title.value = "";',
  '  if (description) description.value = "";',
  '  setIdeaComposerOpen(composer, false);',
  "}",
  "function restoreIdeaDraft(form) {",
  "  var draft = readIdeaDraft(form);",
  "  if (!draft) return;",
  "  var fields = ideaDraftFields(form);",
  "  if (fields.title) fields.title.value = draft.title;",
  "  if (fields.description) fields.description.value = draft.description;",
  '  if (typeof draft.order === "number") form.setAttribute("data-idea-order", String(draft.order));',
  '  if (typeof draft.pinned === "boolean") form.setAttribute("data-idea-pinned", draft.pinned ? "true" : "false");',
  "  updateIdeaPinButton(form);",
  "  resizeIdeaDescription(form);",
  "}",
  "function saveIdeaDraft(form) {",
  "  var key = ideaDraftKey(form);",
  "  if (!key) return;",
  "  var fields = ideaDraftFields(form);",
  "  var draft = { title: fields.title ? fields.title.value : \"\", description: fields.description ? fields.description.value : \"\", pinned: ideaFormPinned(form), order: Number(form.getAttribute(\"data-idea-order\")), updatedAt: Date.now() };",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (error) {}",
  "  syncIdeaCard(form);",
  "}",
  "function createIdeaPin(pinned) {",
  '  var pin = document.createElementNS("http://www.w3.org/2000/svg", "svg");',
  '  pin.setAttribute("class", "idea-card__pin");',
  '  pin.setAttribute("role", "img");',
  '  pin.setAttribute("aria-label", pinned ? "Pinned" : "Not pinned");',
  '  pin.setAttribute("viewBox", "0 0 24 24");',
  '  var path = document.createElementNS("http://www.w3.org/2000/svg", "path");',
  '  path.setAttribute("d", "M16 12V4h1V2H7v2h1v8l-2 2v2h5.8v6h2.4v-6H20v-2z");',
  '  pin.appendChild(path);',
  '  return pin;',
  "}",
  "function updateIdeaCardPin(card, pinned) {",
  '  card.setAttribute("data-pinned", pinned ? "true" : "false");',
  '  var link = card.querySelector(".idea-card__link");',
  '  var pin = card.querySelector(".idea-card__pin");',
  '  if (pinned && !pin && link) {',
  '    pin = createIdeaPin(pinned);',
  '    link.prepend(pin);',
  "  }",
  '  if (pin) pin.setAttribute("aria-label", pinned ? "Pinned" : "Not pinned");',
  "}",
  "function layoutIdeaMasonryGrid(grid) {",
  '  var cards = Array.prototype.slice.call(grid.querySelectorAll(":scope > .idea-card"));',
  '  grid.classList.remove("masonry-ready");',
  '  grid.style.height = "";',
  '  cards.forEach(function (card) { card.style.left = ""; card.style.top = ""; card.style.width = ""; });',
  "  if (cards.length === 0) return;",
  '  var columns = getComputedStyle(grid).gridTemplateColumns.trim().split(/\\s+/).length;',
  '  var gap = 16;',
  '  var columnWidth = (grid.clientWidth - gap * (columns - 1)) / columns;',
  '  cards.forEach(function (card) { card.style.width = columnWidth + "px"; });',
  '  grid.classList.add("masonry-ready");',
  '  var heights = Array(columns).fill(0);',
  '  cards.forEach(function (card) {',
  '    var column = heights.indexOf(Math.min.apply(null, heights));',
  '    card.style.left = (column * (columnWidth + gap)) + "px";',
  '    card.style.top = heights[column] + "px";',
  '    heights[column] += card.offsetHeight + gap;',
  "  });",
  '  grid.style.height = Math.max.apply(null, heights) - gap + "px";',
  "}",
  "function layoutIdeaMasonry() {",
  '  document.querySelectorAll(".ideas-grid").forEach(layoutIdeaMasonryGrid);',
  "}",
  "function updateIdeaGroups() {",
  '  var pinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="pinned"]`);',
  '  var unpinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="unpinned"]`);',
  "  if (!pinnedGrid || !unpinnedGrid) return;",
  '  var cards = Array.prototype.slice.call(document.querySelectorAll(".ideas-grid > .idea-card"));',
  '  cards.sort(function (left, right) { return ideaCardOrder(left) - ideaCardOrder(right); });',
  '  var pinned = cards.filter(function (card) { return card.getAttribute("data-pinned") === "true"; });',
  '  var unpinned = cards.filter(function (card) { return card.getAttribute("data-pinned") !== "true"; });',
  '  var empty = document.querySelector("[data-ideas-empty]");',
  '  if (empty) empty.hidden = cards.length > 0;',
  '  pinned.forEach(function (card) { pinnedGrid.appendChild(card); });',
  '  unpinned.forEach(function (card) { unpinnedGrid.appendChild(card); });',
  '  var gap = document.querySelector("[data-idea-group-gap]");',
  '  if (gap) gap.hidden = pinned.length === 0 || unpinned.length === 0;',
  '  layoutIdeaMasonry();',
  "}",
  "function normalizeIdeaGroupOrder(grid) {",
  '  if (!grid) return;',
  '  var order = 1;',
  '  grid.querySelectorAll(":scope > .idea-card").forEach(function (card) { setIdeaCardOrder(card, order); order += 1; });',
  "}",
  "function nextIdeaOrder(grid) {",
  '  var max = 0;',
  '  if (grid) grid.querySelectorAll(":scope > .idea-card").forEach(function (card) { max = Math.max(max, ideaCardOrder(card)); });',
  '  return max + 1;',
  "}",
  "function createIdeaCard(idea) {",
  '  var card = document.createElement("article");',
  '  card.className = "idea-card";',
  '  card.setAttribute("data-idea-id", idea.id);',
  '  card.setAttribute("data-idea-order", idea.order);',
  '  card.setAttribute("data-order", idea.order);',
  '  card.setAttribute("data-pinned", idea.pinned ? "true" : "false");',
  '  card.setAttribute("draggable", "true");',
  '  var link = document.createElement("a");',
  '  link.className = "idea-card__link";',
  '  link.href = "/ideas/" + encodeURIComponent(idea.id);',
  '  link.appendChild(createIdeaPin(idea.pinned));',
  '  var title = document.createElement("h2");',
  '  title.textContent = idea.title;',
  '  link.appendChild(title);',
  '  var description = document.createElement("p");',
  '  description.className = idea.description ? "idea-card__description" : "idea-card__description idea-card__description--empty";',
  '  description.textContent = idea.description || "No description yet.";',
  '  link.appendChild(description);',
  '  card.appendChild(link);',
  '  var footer = document.createElement("footer");',
  '  footer.className = "idea-card__footer";',
  '  var more = document.createElement("button");',
  '  more.type = "button";',
  '  more.className = "idea-card__more";',
  '  more.setAttribute("aria-label", "More options for " + idea.title);',
  '  var dots = document.createElement("span");',
  '  dots.setAttribute("aria-hidden", "true");',
  '  more.appendChild(dots);',
  '  footer.appendChild(more);',
  '  card.appendChild(footer);',
  '  return card;',
  "}",
  "function restoreCreatedIdeas() {",
  '  var pinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="pinned"]`);',
  '  var unpinnedGrid = document.querySelector(`.ideas-grid[data-idea-group="unpinned"]`);',
  '  if (!pinnedGrid || !unpinnedGrid) return;',
  '  var ideas = readCreatedIdeas();',
  '  var changed = false;',
  '  ideas.forEach(function (idea) {',
  '    if (isIdeaDeleted(idea.id)) return;',
  '    if (ideaCardById(idea.id)) return;',
  '    var grid = idea.pinned ? pinnedGrid : unpinnedGrid;',
  '    if (idea.order < 1) { idea.order = nextIdeaOrder(grid); changed = true; }',
  '    grid.appendChild(createIdeaCard(idea));',
  '  });',
  '  if (changed) writeCreatedIdeas(ideas);',
  "}",
  "function restoreDeletedIdeas() {",
  '  document.querySelectorAll(".idea-card[data-idea-id]").forEach(function (card) {',
  '    var id = ideaCardId(card);',
  '    if (id && isIdeaDeleted(id)) card.remove();',
  '  });',
  "}",
  "function removeIdeaCard(card) {",
  '  var id = ideaCardId(card);',
  '  if (!id) return;',
  '  writeCreatedIdeas(readCreatedIdeas().filter(function (idea) { return idea.id !== id; }));',
  '  if (id.indexOf("created-") !== 0) {',
  '    var deleted = readDeletedIdeas();',
  '    if (deleted.indexOf(id) === -1) { deleted.push(id); writeDeletedIdeas(deleted); }',
  '  }',
  '  try { localStorage.removeItem("siftq.idea-draft:" + id); } catch (error) {}',
  '  card.remove();',
  '  updateIdeaGroups();',
  '  persistIdeaOrders();',
  "}",
  "var ideaMenu = null;",
  "var ideaMenuCard = null;",
  "var ideaDeleteModal = null;",
  "function closeIdeaMenu() {",
  '  if (ideaMenu) ideaMenu.remove();',
  '  ideaMenu = null;',
  '  ideaMenuCard = null;',
  "}",
  "function closeIdeaDeleteModal() {",
  '  if (ideaDeleteModal) ideaDeleteModal.remove();',
  '  ideaDeleteModal = null;',
  "}",
  "function renderIdeaDeleteModal(card) {",
  '  var backdrop = document.createElement("div");',
  '  backdrop.className = "matrix-modal-backdrop";',
  '  var dialog = document.createElement("div");',
  '  dialog.className = "matrix-modal";',
  '  var message = document.createElement("p");',
  '  message.className = "matrix-modal-text";',
  '  message.textContent = "このメモを削除しますか？";',
  '  dialog.appendChild(message);',
  '  var row = document.createElement("div");',
  '  row.className = "matrix-modal-actions";',
  '  var cancelButton = document.createElement("button");',
  '  cancelButton.type = "button";',
  '  cancelButton.className = "matrix-modal-button matrix-modal-button--cancel";',
  '  cancelButton.textContent = "キャンセル";',
  '  cancelButton.setAttribute("data-idea-modal-action", "cancel");',
  '  row.appendChild(cancelButton);',
  '  var confirmButton = document.createElement("button");',
  '  confirmButton.type = "button";',
  '  confirmButton.className = "matrix-modal-button matrix-modal-button--danger";',
  '  confirmButton.textContent = "削除";',
  '  confirmButton.setAttribute("data-idea-modal-action", "confirm");',
  '  row.appendChild(confirmButton);',
  '  dialog.appendChild(row);',
  '  backdrop.addEventListener("click", function (event) {',
  '    var button = event.target.closest ? event.target.closest("[data-idea-modal-action]") : null;',
  '    if (!button) return;',
  '    var action = button.getAttribute("data-idea-modal-action");',
  '    if (action === "confirm") { setTimeout(function () { closeIdeaDeleteModal(); removeIdeaCard(card); }, 0); return; }',
  '    if (action === "cancel") { setTimeout(function () { closeIdeaDeleteModal(); }, 0); return; }',
  '  });',
  '  backdrop.appendChild(dialog);',
  '  document.body.appendChild(backdrop);',
  '  ideaDeleteModal = backdrop;',
  "}",
  "function openIdeaMenu(card, button) {",
  '  closeIdeaMenu();',
  '  ideaMenuCard = card;',
  '  var menu = document.createElement("div");',
  '  menu.className = "matrix-menu";',
  '  var deleteButton = document.createElement("button");',
  '  deleteButton.type = "button";',
  '  deleteButton.className = "matrix-menu-item matrix-menu-item--delete";',
  '  deleteButton.textContent = "削除";',
  '  deleteButton.setAttribute("data-idea-action", "delete");',
  '  menu.appendChild(deleteButton);',
  '  menu.addEventListener("click", function (event) {',
  '    var item = event.target.closest("[data-idea-action]");',
  '    if (!item) return;',
  '    if (item.getAttribute("data-idea-action") === "delete") { var target = ideaMenuCard; closeIdeaMenu(); renderIdeaDeleteModal(target); }',
  '  });',
  '  document.body.appendChild(menu);',
  '  var rect = button.getBoundingClientRect();',
  '  var menuRect = menu.getBoundingClientRect();',
  '  menu.style.left = Math.max(8, Math.min(rect.left, window.innerWidth - menuRect.width - 8)) + "px";',
  '  menu.style.top = Math.max(8, Math.min(rect.bottom + 4, window.innerHeight - menuRect.height - 8)) + "px";',
  '  ideaMenu = menu;',
  "}",
  "function syncIdeaCard(form) {",
  '  var id = form.getAttribute("data-idea-id");',
  '  var card = id ? ideaCardById(id) : null;',
  "  if (!card) return;",
  '  var fields = ideaDraftFields(form);',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  if (title && fields.title) title.textContent = fields.title.value;',
  '  if (description && fields.description) description.textContent = fields.description.value || "No description yet.";',
  '  if (description) description.classList.toggle("idea-card__description--empty", !fields.description || !fields.description.value);',
  '  var order = Number(form.getAttribute("data-idea-order"));',
  '  if (Number.isFinite(order)) setIdeaCardOrder(card, order);',
  '  updateIdeaCardPin(card, ideaFormPinned(form));',
  "  updateIdeaGroups();",
  "  persistIdeaOrders();",
  "}",
  "function moveIdeaCardToGroup(card, pinned) {",
  '  var current = card.getAttribute("data-pinned") === "true";',
  '  if (current === pinned) return;',
  '  var target = document.querySelector(`.ideas-grid[data-idea-group="${pinned ? "pinned" : "unpinned"}"]`);',
  '  if (target) setIdeaCardOrder(card, nextIdeaOrder(target));',
  "}",
  "function setIdeaPinned(form, pinned) {",
  '  form.setAttribute("data-idea-pinned", pinned ? "true" : "false");',
  '  var card = ideaCardById(form.getAttribute("data-idea-id"));',
  '  if (card) moveIdeaCardToGroup(card, pinned);',
  '  if (card) form.setAttribute("data-idea-order", card.getAttribute("data-idea-order") || "");',
  "  updateIdeaPinButton(form);",
  "  saveIdeaDraft(form);",
  "}",
  "function toggleIdeaCardPin(card) {",
  '  var id = ideaCardId(card);',
  '  if (!id) return;',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  var pinned = card.getAttribute("data-pinned") !== "true";',
  '  moveIdeaCardToGroup(card, pinned);',
  '  var draft = { title: title ? title.textContent || "" : "", description: description ? description.textContent || "" : "", pinned: pinned, order: ideaCardOrder(card), updatedAt: Date.now() };',
  '  try { localStorage.setItem("siftq.idea-draft:" + id, JSON.stringify(draft)); } catch (error) {}',
  '  updateIdeaCardPin(card, pinned);',
  "  updateIdeaGroups();",
  "  persistIdeaOrders();",
  "}",
  "function scheduleIdeaDraftSave(form) {",
  '  if (form._ideaDraftTimer) clearTimeout(form._ideaDraftTimer);',
  "  form._ideaDraftTimer = setTimeout(function () { saveIdeaDraft(form); }, 400);",
  "}",
  "function restoreIdeaCardDrafts() {",
  '  document.querySelectorAll(".idea-card[data-idea-id]").forEach(function (card) {',
  '    var id = ideaCardId(card);',
  '    if (!id) return;',
  '    var raw;',
  '    try { raw = localStorage.getItem("siftq.idea-draft:" + id); } catch (error) { return; }',
  '    if (!raw) return;',
  '    var draft;',
  '    try { draft = JSON.parse(raw); } catch (error) { return; }',
  '    if (!draft || typeof draft.title !== "string" || typeof draft.description !== "string") return;',
  '    var title = card.querySelector("h2");',
  '    var description = card.querySelector(".idea-card__description");',
  '    if (title) title.textContent = draft.title;',
  '    if (description) description.textContent = draft.description || "No description yet.";',
  '    if (typeof draft.order === "number" && Number.isFinite(draft.order)) setIdeaCardOrder(card, draft.order);',
  '    if (typeof draft.pinned === "boolean") updateIdeaCardPin(card, draft.pinned);',
  "  });",
  "  updateIdeaGroups();",
  "}",
  "function createNewIdea(title, description) {",
  '  if (!title && !description) return;',
  '  var id = "created-" + Date.now() + "-" + Math.random().toString(36).slice(2, 8);',
  '  var grid = document.querySelector(`.ideas-grid[data-idea-group="unpinned"]`);',
  '  var idea = { id: id, order: nextIdeaOrder(grid), title: title || "無題", description: description, pinned: false };',
  '  var ideas = readCreatedIdeas();',
  '  ideas.push(idea);',
  '  writeCreatedIdeas(ideas);',
  '  if (grid) grid.appendChild(createIdeaCard(idea));',
  '  updateIdeaGroups();',
  '  persistIdeaOrders();',
  "}",
  "function initializeIdeaComposer() {",
  '  document.querySelectorAll("[data-idea-composer]").forEach(function (composer) {',
  '    if (composer.dataset.ideaComposerInitialized === "true") return;',
  '    composer.dataset.ideaComposerInitialized = "true";',
  '    setIdeaComposerOpen(composer, false);',
  '    var trigger = composer.querySelector("[data-idea-composer-trigger]");',
  '    var close = composer.querySelector("[data-idea-composer-close]");',
  '    var description = composer.querySelector(".ideas-composer__description");',
  '    if (trigger) trigger.addEventListener("click", function () { setIdeaComposerOpen(composer, true); });',
  '    if (close) close.addEventListener("click", function () { finishIdeaComposer(composer); });',
  '    if (description) description.addEventListener("input", function () { resizeIdeaComposer(composer); });',
  '    document.addEventListener("click", function (event) {',
  '      if (composer.getAttribute("data-idea-composer-open") !== "true" || event.target.closest("[data-idea-composer]")) return;',
  '      finishIdeaComposer(composer);',
  '    });',
  "  });",
  "}",
  "function openIdeaModal(card) {",
  '  var modal = document.querySelector("[data-idea-modal]");',
  '  var form = modal ? modal.querySelector("form[data-idea-form]") : null;',
  "  if (!modal || !form) return;",
  '  var id = ideaCardId(card);',
  '  var order = card.getAttribute("data-idea-order");',
  '  var title = card.querySelector("h2");',
  '  var description = card.querySelector(".idea-card__description");',
  '  form.setAttribute("data-idea-id", id || "");',
  '  form.setAttribute("data-idea-order", order || "");',
  '  form.setAttribute("data-idea-mode", "edit");',
  '  form.setAttribute("data-idea-pinned", card.getAttribute("data-pinned") === "true" ? "true" : "false");',
  "  var fields = ideaDraftFields(form);",
  '  if (fields.title) fields.title.value = title ? title.textContent || "" : "";',
  '  if (fields.description) fields.description.value = description ? description.textContent || "" : "";',
  "  updateIdeaPinButton(form);",
  "  resizeIdeaDescription(form);",
  "  restoreIdeaDraft(form);",
  '  var close = modal.querySelector("[data-idea-close]");',
  '  if (close) close.textContent = "閉じる";',
  '  if (typeof modal.showModal === "function" && !modal.open) modal.showModal();',
  "  resizeIdeaDescription(form);",
  "}",
  "function initializeIdeaDetails() {",
  "  initializeIdeaComposer();",
  "  restoreDeletedIdeas();",
  "  restoreCreatedIdeas();",
  "  restoreIdeaOrders();",
  "  restoreIdeaCardDrafts();",
  '  document.querySelectorAll("form[data-idea-form]").forEach(function (form) {',
  '    if (form.dataset.ideaDetailInitialized === "true") return;',
  '    form.dataset.ideaDetailInitialized = "true";',
  "    restoreIdeaDraft(form);",
  '    updateIdeaPinButton(form);',
  '    resizeIdeaDescription(form);',
  '    form.addEventListener("input", function () { resizeIdeaDescription(form); scheduleIdeaDraftSave(form); });',
  '    var pin = form.querySelector("[data-idea-pin]");',
  '    if (pin) pin.addEventListener("click", function () { setIdeaPinned(form, !ideaFormPinned(form)); });',
  "  });",
  '  document.querySelectorAll("[data-idea-modal]").forEach(function (modal) {',
  '    if (modal.dataset.ideaModalInitialized === "true") return;',
  '    modal.dataset.ideaModalInitialized = "true";',
  '    var close = modal.querySelector("[data-idea-close]");',
   '    if (close) close.addEventListener("click", function () { modal.close(); });',
  '    document.addEventListener("click", function (event) {',
  '      if (!modal.open) return;',
   '      if (event.target.closest(".idea-card") || event.target.closest(".ideas-composer")) return;',
  '      var box = modal.getBoundingClientRect();',
  '      var outside = event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom;',
    '      if (outside || event.target === modal) modal.close();',
  '    });',
  "  });",
  "}",
  'document.addEventListener("DOMContentLoaded", initializeIdeaDetails);',
  'document.addEventListener("htmx:load", initializeIdeaDetails);',
  'window.addEventListener("resize", layoutIdeaMasonry);',
  'document.addEventListener("click", function (event) {',
  '  if (!ideaMenu || ideaMenu.contains(event.target)) return;',
  '  closeIdeaMenu();',
  '}, true);',
    'document.addEventListener("click", function (event) {',
    '  var modal = document.querySelector("[data-idea-modal]");',
    '  if (modal && modal.open) return;',
    '  if (document.querySelector(`[data-idea-composer][data-idea-composer-open="true"]`)) return;',
    '  var card = event.target.closest(".idea-card[data-idea-id]");',
    '  var id = card ? ideaCardId(card) : null;',
    '  if (!card || !id) return;',
   '  var more = event.target.closest(".idea-card__more");',
   '  if (more) { event.preventDefault(); openIdeaMenu(card, more); return; }',
  '  if (event.target.closest(".idea-card__pin")) { event.preventDefault(); toggleIdeaCardPin(card); return; }',
  '  event.preventDefault();',
  '  openIdeaModal(card);',
  "});",
].join("\n");
*/
