export const MATRIX_DND_SCRIPT = [
  "let matrixDraggingCard = null;",
  "let matrixDragPointerId = null;",
  "let matrixDragStart = null;",
  "let matrixDropTarget = null;",
  "let matrixDndPending = false;",
  "let suppressMatrixCardClick = false;",
  "let matrixAutoScrollFrame = null;",
  "let matrixAutoScrollList = null;",
  "let matrixAutoScrollDelta = 0;",
  "let matrixDragGhost = null;",
  "let matrixDragPlaceholder = null;",
  "let matrixDragGrabOffset = null;",
  "const MATRIX_DRAG_THRESHOLD = 5;",
  "function showDndConflict() {",
  "  const notice = document.getElementById(\"dnd-conflict\");",
  "  if (notice) notice.hidden = false;",
  "}",
  "function restoreMatrix() {",
  "  fetch(\"/\", { headers: { \"HX-Request\": \"true\" } })",
  "    .then(function (response) { return response.text(); })",
  "    .then(function (html) {",
  "      const page = document.getElementById(\"page\");",
  "      if (page) page.innerHTML = html;",
  "      showDndConflict();",
  "      initMatrixDnd();",
  "    });",
  "}",
  "function matrixCards(list) {",
  "  return Array.prototype.slice.call(list.querySelectorAll(\":scope > .task-card\"));",
  "}",
  "function matrixDropIndex(list, pointerY) {",
  "  const cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  for (let index = 0; index < cards.length; index += 1) {",
  "    const box = cards[index].getBoundingClientRect();",
  "    if (pointerY < box.top + box.height / 2) return index;",
  "  }",
  "  return cards.length;",
  "}",
  "function matrixDropListFromPoint(x, y) {",
  "  const element = document.elementFromPoint(x, y);",
  "  const quadrant = element && element.closest ? element.closest(\".area--quadrant[data-drop-area]\") : null;",
  "  return quadrant ? quadrant.querySelector(\".matrix-cards[data-dnd-group]\") : null;",
  "}",
  "function setMatrixDropTarget(target) {",
  "  if (matrixDropTarget === target) return;",
  "  if (matrixDropTarget) matrixDropTarget.closest(\".area--quadrant\").classList.remove(\"drop-target\");",
  "  matrixDropTarget = target;",
  "  if (matrixDropTarget) matrixDropTarget.closest(\".area--quadrant\").classList.add(\"drop-target\");",
  "}",
  "function stopMatrixAutoScroll() {",
  "  if (matrixAutoScrollFrame !== null) {",
  "    window.cancelAnimationFrame(matrixAutoScrollFrame);",
  "    matrixAutoScrollFrame = null;",
  "  }",
  "  matrixAutoScrollList = null;",
  "  matrixAutoScrollDelta = 0;",
  "}",
  "function stepMatrixAutoScroll() {",
  "  matrixAutoScrollFrame = null;",
  "  if (!matrixAutoScrollList || matrixAutoScrollDelta === 0) return;",
  "  matrixAutoScrollList.scrollTop += matrixAutoScrollDelta * 14;",
  "  matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function updateMatrixAutoScroll(pointerY, list) {",
  "  if (!list || list.scrollHeight <= list.clientHeight) { stopMatrixAutoScroll(); return; }",
  "  const box = list.getBoundingClientRect();",
  "  const edge = 32;",
  "  const delta = pointerY < box.top + edge ? -1 : pointerY > box.bottom - edge ? 1 : 0;",
  "  if (delta === 0) { stopMatrixAutoScroll(); return; }",
  "  matrixAutoScrollList = list;",
  "  matrixAutoScrollDelta = delta;",
  "  if (matrixAutoScrollFrame === null) matrixAutoScrollFrame = window.requestAnimationFrame(stepMatrixAutoScroll);",
  "}",
  "function clearMatrixDnd() {",
  "  if (matrixDraggingCard) matrixDraggingCard.classList.remove(\"dragging\");",
  "  if (matrixDragGhost) { matrixDragGhost.remove(); matrixDragGhost = null; }",
  "  if (matrixDragPlaceholder) { matrixDragPlaceholder.remove(); matrixDragPlaceholder = null; }",
  "  matrixDragGrabOffset = null;",
  "  setMatrixDropTarget(null);",
  "  stopMatrixAutoScroll();",
  "  matrixDraggingCard = null;",
  "  matrixDragPointerId = null;",
  "  matrixDragStart = null;",
  "}",
  "function setMatrixDndPending(pending) {",
  "  matrixDndPending = pending;",
  "}",
  "function matrixCardFromEvent(event) {",
  "  const element = event.target;",
  "  return element && element.closest ? element.closest(\".matrix-cards .task-card\") : null;",
  "}",
  "function positionMatrixGhost(x, y) {",
  "  if (!matrixDragGhost || !matrixDragGrabOffset) return;",
  "  matrixDragGhost.style.left = (x - matrixDragGrabOffset.x) + 'px';",
  "  matrixDragGhost.style.top = (y - matrixDragGrabOffset.y) + 'px';",
  "}",
  "function positionMatrixPlaceholder(list, pointerY) {",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  if (!list || !matrixDragPlaceholder) return;",
  "  const cards = matrixCards(list).filter(function (card) { return card !== matrixDraggingCard; });",
  "  const index = matrixDropIndex(list, pointerY);",
  "  list.insertBefore(matrixDragPlaceholder, cards[index] || null);",
  "}",
  "function updateMatrixDrag(event) {",
  "  positionMatrixGhost(event.clientX, event.clientY);",
  "  const target = matrixDropListFromPoint(event.clientX, event.clientY);",
  "  setMatrixDropTarget(target);",
  "  positionMatrixPlaceholder(target, event.clientY);",
  "  updateMatrixAutoScroll(event.clientY, target);",
  "}",
  "function startMatrixDrag(event) {",
  "  matrixDraggingCard.classList.add(\"dragging\");",
  "  suppressMatrixCardClick = true;",
  "  try { matrixDraggingCard.setPointerCapture(matrixDragPointerId); } catch (error) {}",
  "  const rect = matrixDraggingCard.getBoundingClientRect();",
  "  matrixDragGrabOffset = { x: event.clientX - rect.left, y: event.clientY - rect.top };",
  "  const ghost = matrixDraggingCard.cloneNode(true);",
  "  ghost.classList.remove(\"dragging\");",
  "  ghost.classList.add(\"matrix-drag-ghost\");",
  "  ghost.style.width = rect.width + \"px\";",
  "  document.body.appendChild(ghost);",
  "  matrixDragGhost = ghost;",
  "  const placeholder = document.createElement(\"div\");",
  "  placeholder.className = \"drop-line matrix-drag-placeholder\";",
  "  placeholder.style.height = rect.height + \"px\";",
  "  matrixDragPlaceholder = placeholder;",
  "  updateMatrixDrag(event);",
  "}",
  "function finishMatrixDrag(event) {",
  "  const card = matrixDraggingCard;",
  "  const target = matrixDropTarget;",
  "  if (matrixDragPlaceholder) matrixDragPlaceholder.remove();",
  "  const index = target ? matrixDropIndex(target, event.clientY) : 0;",
  "  clearMatrixDnd();",
  "  setTimeout(function () { suppressMatrixCardClick = false; }, 0);",
  "  if (!target) return;",
  "  const cards = matrixCards(target).filter(function (candidate) { return candidate !== card; });",
  "  const reference = cards[index] || null;",
  "  target.insertBefore(card, reference);",
  "  persistMatrixDrop(card, target);",
  "}",
  "function initMatrixDnd() {",
  "  clearMatrixDnd();",
  "}",
  "function persistMatrixDrop(card, target) {",
  "  const taskId = card.getAttribute(\"data-task-id\");",
  "  const version = card.getAttribute(\"data-version\");",
  "  const area = target.getAttribute(\"data-area\");",
  "  const order = matrixCards(target).indexOf(card);",
  "  if (!taskId || !version || area === null || order < 0) return;",
  "  setMatrixDndPending(true);",
  "  return fetch(\"/api/tasks/reorder\", {",
  "    method: \"POST\",",
  "    headers: { \"Content-Type\": \"application/json\" },",
  "    body: JSON.stringify({ id: taskId, area: Number(area), order: order, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) { showDndConflict(); restoreMatrix(); return null; }",
  "    return response.json();",
  "  }).then(function (tasks) {",
  "    if (!Array.isArray(tasks)) return;",
  "    tasks.forEach(function (task) {",
  "      if (!task || typeof task.id !== \"string\" || typeof task.version !== \"number\") return;",
  "      document.querySelectorAll(\".task-card[data-task-id]\").forEach(function (updatedCard) {",
  "        if (updatedCard.getAttribute(\"data-task-id\") === task.id) {",
  "          updatedCard.setAttribute(\"data-version\", String(task.version));",
  "        }",
  "      });",
  "    });",
  "  }).finally(function () { setMatrixDndPending(false); });",
  "}",
  "document.addEventListener(\"pointerdown\", function (event) {",
  "  if (event.button !== 0 || !event.isPrimary || matrixDndPending || matrixDraggingCard) return;",
  "  const card = matrixCardFromEvent(event);",
  "  if (!card || !card.getAttribute(\"data-task-id\")) return;",
  "  matrixDraggingCard = card;",
  "  matrixDragPointerId = event.pointerId;",
  "  matrixDragStart = { x: event.clientX, y: event.clientY };",
  "});",
  "document.addEventListener(\"pointermove\", function (event) {",
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  "  if (!matrixDraggingCard.classList.contains(\"dragging\")) {",
  "    const dx = event.clientX - matrixDragStart.x;",
  "    const dy = event.clientY - matrixDragStart.y;",
  "    if (Math.abs(dx) < MATRIX_DRAG_THRESHOLD && Math.abs(dy) < MATRIX_DRAG_THRESHOLD) return;",
  "    startMatrixDrag(event);",
  "    return;",
  "  }",
  "  event.preventDefault();",
  "  updateMatrixDrag(event);",
  "});",
  "document.addEventListener(\"pointerup\", function (event) {",
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  "  if (matrixDraggingCard.classList.contains(\"dragging\")) { finishMatrixDrag(event); return; }",
  "  clearMatrixDnd();",
  "});",
  "document.addEventListener(\"pointercancel\", function (event) {",
  "  if (!matrixDraggingCard || event.pointerId !== matrixDragPointerId) return;",
  "  clearMatrixDnd();",
  "});",
  "document.addEventListener(\"click\", function (event) {",
  "  if (!suppressMatrixCardClick) return;",
  "  const card = matrixCardFromEvent(event);",
  "  if (!card) return;",
  "  event.preventDefault();",
  "  event.stopPropagation();",
  "  suppressMatrixCardClick = false;",
  "}, true);",
  "document.addEventListener(\"click\", function (event) {",
  "  if (event.defaultPrevented) return;",
  "  if (event.target.closest(\"a, button, input, select, textarea\")) return;",
  "  const quadrant = event.target.closest(\".area--quadrant[data-drop-area]\");",
  "  if (!quadrant) return;",
  "  const area = quadrant.getAttribute(\"data-drop-area\");",
  "  if (area === null) return;",
  "  window.location.assign(\"/tasks/new?area=\" + encodeURIComponent(area) + \"&from=matrix\");",
  "});",
  "document.addEventListener(\"DOMContentLoaded\", initMatrixDnd);",
  "document.addEventListener(\"htmx:load\", initMatrixDnd);",
  "let matrixMenu = null;",
  "let matrixMenuCard = null;",
  "let matrixActionPending = false;",
  "let matrixMenuJustOpened = false;",
  "function closeMatrixMenu() {",
  "  if (!matrixMenu) return;",
  "  matrixMenu.remove();",
  "  matrixMenu = null;",
  "  matrixMenuCard = null;",
  "  matrixMenuJustOpened = false;",
  "}",
  "function removeMatrixCard(card) {",
  "  if (card) card.remove();",
  "  matrixMenuCard = null;",
  "}",
  "function setMatrixActionPending(pending) {",
  "  matrixActionPending = pending;",
  "  setMatrixDndPending(pending);",
  "}",
  "function restoreMatrixAfterAction() {",
  "  showDndConflict();",
  "  return restoreMatrix();",
  "}",
  "function persistMatrixStatus(card, status) {",
  "  const taskId = card.getAttribute(\"data-task-id\");",
  "  const version = card.getAttribute(\"data-version\");",
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  "  fetch(\"/api/tasks/\" + encodeURIComponent(taskId), {",
  "    method: \"PATCH\",",
  "    headers: { \"Content-Type\": \"application/json\" },",
  "    body: JSON.stringify({ status: status, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) removeMatrixCard(card);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function setMatrixCardWorking(card, working, version) {",
  "  if (typeof version === \"number\") card.setAttribute(\"data-version\", String(version));",
  "  const header = card.querySelector(\".task-card-header\");",
  "  let badge = card.querySelector(\".working-badge\");",
  "  if (working) {",
  "    card.classList.add(\"task-card--working\");",
  "    if (!badge && header) {",
  "      badge = document.createElement(\"span\");",
  "      badge.className = \"working-badge\";",
  "      badge.textContent = \"working\";",
  "      header.appendChild(badge);",
  "    }",
  "  } else {",
  "    card.classList.remove(\"task-card--working\");",
  "    if (badge) badge.remove();",
  "  }",
  "}",
  "function persistMatrixWorking(card, working) {",
  "  const taskId = card.getAttribute(\"data-task-id\");",
  "  const version = card.getAttribute(\"data-version\");",
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  setTimeout(function () { closeMatrixMenu(); }, 0);",
  "  fetch(\"/api/tasks/\" + encodeURIComponent(taskId), {",
  "    method: \"PATCH\",",
  "    headers: { \"Content-Type\": \"application/json\" },",
  "    body: JSON.stringify({ working: working, version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction().then(function () { return null; });",
  "    return response.json();",
  "  }).then(function (task) {",
  "    if (task) setMatrixCardWorking(card, task.working === true, task.version);",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function persistMatrixDelete(card) {",
  "  const taskId = card.getAttribute(\"data-task-id\");",
  "  const version = card.getAttribute(\"data-version\");",
  "  if (!taskId || !version) return;",
  "  setMatrixActionPending(true);",
  "  fetch(\"/api/tasks/\" + encodeURIComponent(taskId), {",
  "    method: \"DELETE\",",
  "    headers: { \"Content-Type\": \"application/json\" },",
  "    body: JSON.stringify({ version: Number(version) }),",
  "  }).then(function (response) {",
  "    if (!response.ok) return restoreMatrixAfterAction();",
  "    if (typeof removeTaskDraft === \"function\") removeTaskDraft(taskId);",
  "    removeMatrixCard(card);",
  "    return null;",
  "  }).finally(function () { setMatrixActionPending(false); });",
  "}",
  "function renderMatrixMenuItems(menu, card) {",
  "  const actions = [",
  "    { key: \"delete\", label: \"delete\" },",
  "    { key: \"skip\", label: \"skip\" },",
  "    { key: \"done\", label: \"done\" },",
  "  ];",
  "  const working = card && card.classList.contains(\"task-card--working\");",
  "  actions.push({ key: \"working\", label: working ? \"working: on\" : \"working: off\" });",
  "  actions.forEach(function (action) {",
  "    const item = document.createElement(\"button\");",
  "    item.type = \"button\";",
  "    item.className = \"matrix-menu-item matrix-menu-item--\" + action.key;",
  "    item.textContent = action.label;",
  "    item.setAttribute(\"data-matrix-action\", action.key);",
  "    menu.appendChild(item);",
  "  });",
  "}",
  "let matrixModal = null;",
  "function closeMatrixModal() {",
  "  if (!matrixModal) return;",
  "  matrixModal.remove();",
  "  matrixModal = null;",
  "  matrixMenuCard = null;",
  "}",
  "function renderMatrixDeleteModal(card) {",
  "  const backdrop = document.createElement(\"div\");",
  "  backdrop.className = \"matrix-modal-backdrop\";",
  "  const dialog = document.createElement(\"div\");",
  "  dialog.className = \"matrix-modal\";",
  "  const message = document.createElement(\"p\");",
  "  message.className = \"matrix-modal-text\";",
  "  message.textContent = \"このタスクを削除しますか？\";",
  "  dialog.appendChild(message);",
  "  const row = document.createElement(\"div\");",
  "  row.className = \"matrix-modal-actions\";",
  "  const cancelButton = document.createElement(\"button\");",
  "  cancelButton.type = \"button\";",
  "  cancelButton.className = \"matrix-modal-button matrix-modal-button--cancel\";",
  "  cancelButton.textContent = \"キャンセル\";",
  "  cancelButton.setAttribute(\"data-matrix-modal-action\", \"cancel\");",
  "  row.appendChild(cancelButton);",
  "  const confirmButton = document.createElement(\"button\");",
  "  confirmButton.type = \"button\";",
  "  confirmButton.className = \"matrix-modal-button matrix-modal-button--danger\";",
  "  confirmButton.textContent = \"削除\";",
  "  confirmButton.setAttribute(\"data-matrix-modal-action\", \"confirm\");",
  "  row.appendChild(confirmButton);",
  "  dialog.appendChild(row);",
  "  backdrop.addEventListener(\"click\", function (event) {",
  "    const button = event.target.closest ? event.target.closest(\"[data-matrix-modal-action]\") : null;",
  "    if (!button) return;",
  "    const action = button.getAttribute(\"data-matrix-modal-action\");",
  "    if (action === \"confirm\") { setTimeout(function () { closeMatrixModal(); persistMatrixDelete(card); }, 0); return; }",
  "    if (action === \"cancel\") { setTimeout(function () { closeMatrixModal(); }, 0); return; }",
  "  });",
  "  backdrop.appendChild(dialog);",
  "  document.body.appendChild(backdrop);",
  "  matrixModal = backdrop;",
  "}",
  "function openMatrixMenu(card, x, y) {",
  "  closeMatrixMenu();",
  "  matrixMenuCard = card;",
  "  const taskId = card.getAttribute(\"data-task-id\") || \"\";",
  "  const menu = document.createElement(\"div\");",
  "  menu.className = \"matrix-menu\";",
  "  renderMatrixMenuItems(menu, card);",
  "  menu.addEventListener(\"click\", function (event) {",
  "    const item = event.target.closest(\"[data-matrix-action]\");",
  "    if (!item) return;",
  "    const action = item.getAttribute(\"data-matrix-action\");",
  "    if (action === \"done\" || action === \"skip\") { persistMatrixStatus(matrixMenuCard, action); return; }",
  "    if (action === \"working\") {",
  "      const workingCard = matrixMenuCard;",
  "      const working = workingCard && !workingCard.classList.contains(\"task-card--working\");",
  "      persistMatrixWorking(workingCard, working);",
  "      return;",
  "    }",
  "    if (action === \"delete\") {",
  "      const card = matrixMenuCard;",
  "      setTimeout(function () { closeMatrixMenu(); renderMatrixDeleteModal(card); }, 0);",
  "      return;",
  "    }",
  "  });",
  "  document.body.appendChild(menu);",
  "  const rect = menu.getBoundingClientRect();",
  "  menu.style.left = Math.max(8, Math.min(x, window.innerWidth - rect.width - 8)) + 'px';",
  "  menu.style.top = Math.max(8, Math.min(y, window.innerHeight - rect.height - 8)) + 'px';",
  "  matrixMenu = menu;",
  "  matrixMenuJustOpened = true;",
  "  void taskId;",
  "}",
  "document.addEventListener(\"contextmenu\", function (event) {",
  "  const card = event.target.closest ? event.target.closest(\".matrix-cards .task-card\") : null;",
  "  if (!card || matrixActionPending) return;",
  "  event.preventDefault();",
  "  openMatrixMenu(card, event.clientX, event.clientY);",
  "});",
  "document.addEventListener(\"click\", function (event) {",
  "  if (!matrixMenu) return;",
  "  if (matrixMenu.contains(event.target)) { matrixMenuJustOpened = false; return; }",
  "  if (matrixMenuJustOpened) { matrixMenuJustOpened = false; return; }",
  "  closeMatrixMenu();",
  "}, true);",
].join("\n");
