export const DESCRIPTION_EDITOR_SCRIPT = [
  "function descriptionEditorValue(editor) {",
  "  return editor.innerText.replace(/\\n$/, \"\");",
  "}",
  "function syncDescriptionEditor(editor) {",
  "  const form = editor.closest(\"form\");",
  "  const hidden = form ? form.querySelector(\"textarea[data-description-value]\") : null;",
  "  if (hidden) hidden.value = descriptionEditorValue(editor);",
  "}",
  "function linkifyDescriptionEditor(editor) {",
  "  const walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);",
  "  const nodes = [];",
  "  while (walker.nextNode()) nodes.push(walker.currentNode);",
  "  nodes.forEach(function (node) {",
  "    if (!node.parentElement || node.parentElement.closest(\"a\")) return;",
  "    const text = node.nodeValue || \"\";",
  "    const pattern = /https?:\\/\\/[^\\s<>]+/g;",
  "    let match;",
  "    let cursor = 0;",
  "    const fragment = document.createDocumentFragment();",
  "    let changed = false;",
  "    while ((match = pattern.exec(text)) !== null) {",
  "      const raw = match[0];",
  "      const url = raw.replace(/[.,!?;:]+$/, \"\");",
  "      if (!url) continue;",
  "      if (match.index > cursor) fragment.appendChild(document.createTextNode(text.slice(cursor, match.index)));",
  "      const link = document.createElement(\"a\");",
  "      link.href = url;",
  "      link.textContent = url;",
  "      fragment.appendChild(link);",
  "      if (raw.length > url.length) fragment.appendChild(document.createTextNode(raw.slice(url.length)));",
  "      cursor = match.index + raw.length;",
  "      changed = true;",
  "    }",
  "    if (!changed) return;",
  "    if (cursor < text.length) fragment.appendChild(document.createTextNode(text.slice(cursor)));",
  "    node.parentNode.replaceChild(fragment, node);",
  "  });",
  "}",
  "function initializeDescriptionEditors() {",
  "  document.querySelectorAll(\"[data-description-editor]\").forEach(function (editor) {",
  "    if (editor.dataset.descriptionEditorInitialized === \"true\") { syncDescriptionEditor(editor); return; }",
  "    editor.dataset.descriptionEditorInitialized = \"true\";",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "    editor.addEventListener(\"input\", function () { syncDescriptionEditor(editor); });",
  "    editor.addEventListener(\"click\", function (event) {",
  "      const link = event.target && event.target.closest ? event.target.closest(\"a\") : null;",
  "      if (!link || !editor.contains(link)) return;",
  "      event.preventDefault();",
  "      if (event.ctrlKey || event.metaKey) {",
  "        window.open(link.href, \"_blank\", \"noopener,noreferrer\");",
  "      } else {",
  "        window.location.assign(link.href);",
  "      }",
  "    });",
  "    editor.addEventListener(\"paste\", function (event) {",
  "      const text = event.clipboardData ? event.clipboardData.getData(\"text/plain\") : \"\";",
  "      if (!text) return;",
  "      event.preventDefault();",
  "      document.execCommand(\"insertText\", false, text);",
  "      linkifyDescriptionEditor(editor);",
  "      syncDescriptionEditor(editor);",
  "    });",
  "  });",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeDescriptionEditors);",
  "document.addEventListener(\"htmx:load\", initializeDescriptionEditors);",
  "function taskFormDraftKey(form) {",
  "  if (form.getAttribute(\"data-task-form\") === \"new\") return null;",
  "  const action = form.getAttribute(\"action\") || \"\";",
  "  const match = action.match(/\\/tasks\\/([^/?#]+)/);",
  "  if (match) return \"siftq.task-draft:\" + decodeURIComponent(match[1]);",
  "  return null;",
  "}",
  "function removeTaskDraft(taskId) {",
  "  if (!taskId) return;",
  "  try { localStorage.removeItem(\"siftq.task-draft:\" + taskId); } catch (e) {}",
  "}",
  "function taskFormDraftVersion(form) {",
  "  const versionInput = form.querySelector(\"#task-version\");",
  "  if (!versionInput) return null;",
  "  const version = Number(versionInput.value);",
  "  return Number.isFinite(version) ? version : null;",
  "}",
  "function saveTaskFormDraft(form) {",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  const titleInput = form.querySelector('input[name=\"title\"]');",
  "  const hidden = form.querySelector(\"textarea[data-description-value]\");",
  "  const editor = form.querySelector(\"[data-description-editor]\");",
  "  const title = titleInput ? titleInput.value : \"\";",
  "  const description = hidden ? hidden.value : editor ? descriptionEditorValue(editor) : \"\";",
  "  const draft = { title: title, description: description, updatedAt: Date.now() };",
  "  const version = taskFormDraftVersion(form);",
  "  if (version !== null) draft.version = version;",
  "  try {",
  "    localStorage.setItem(key, JSON.stringify(draft));",
  "  } catch (e) {}",
  "}",
  "function scheduleTaskFormDraft(form) {",
  "  if (form._taskDraftTimer) clearTimeout(form._taskDraftTimer);",
  "  form._taskDraftTimer = setTimeout(function () { saveTaskFormDraft(form); }, 500);",
  "}",
  "function restoreTaskFormDraft(form) {",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  let raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  let draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  "  if (!draft || typeof draft.title !== \"string\" || typeof draft.description !== \"string\") return;",
  "  if (typeof draft.updatedAt === 'number' && Date.now() - draft.updatedAt >= 24 * 60 * 60 * 1000) {",
  "    try { localStorage.removeItem(key); } catch (e) {}",
  "    return;",
  "  }",
  "  if (typeof draft.version === 'number') {",
  "    const serverVersion = taskFormDraftVersion(form);",
  "    if (serverVersion !== null && serverVersion !== draft.version) {",
  "      try { localStorage.removeItem(key); } catch (e) {}",
  "      return;",
  "    }",
  "  }",
  "  const titleInput = form.querySelector('input[name=\"title\"]');",
  "  if (titleInput) titleInput.value = draft.title;",
  "  const editor = form.querySelector(\"[data-description-editor]\");",
  "  if (editor) {",
  "    editor.textContent = draft.description;",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "  } else {",
  "    const hidden = form.querySelector(\"textarea[data-description-value]\");",
  "    if (hidden) hidden.value = draft.description;",
  "  }",
  "}",
  "function initializeTaskFormDrafts() {",
  "  document.querySelectorAll(\"form[data-task-form]\").forEach(function (form) {",
  "    if (form.dataset.taskDraftInitialized === \"true\") return;",
  "    form.dataset.taskDraftInitialized = \"true\";",
  "    restoreTaskFormDraft(form);",
  "    form.addEventListener(\"input\", function () { scheduleTaskFormDraft(form); });",
  "  });",
  "}",
  "function refreshTaskFormDraftVersion() {",
  "  const form = document.querySelector('form[data-task-form=\"edit\"]');",
  "  if (!form) return;",
  "  const version = taskFormDraftVersion(form);",
  "  if (version === null) return;",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  let raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  let draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  "  if (!draft || typeof draft.title !== \"string\" || typeof draft.description !== \"string\") return;",
  "  if (draft.version === version) return;",
  "  draft.version = version;",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (e) {}",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeTaskFormDrafts);",
  "document.addEventListener(\"htmx:load\", initializeTaskFormDrafts);",
  "document.body.addEventListener(\"htmx:oobAfterSwap\", refreshTaskFormDraftVersion);",
  "document.body.addEventListener(\"htmx:afterSettle\", refreshTaskFormDraftVersion);",
  "document.body.addEventListener(\"htmx:afterRequest\", function (event) {",
  "  const detail = event.detail || {};",
  "  const xhr = detail.xhr;",
  "  const status = xhr ? xhr.status : 0;",
  "  if (status < 200 || status >= 300) return;",
  "  try { if (xhr && typeof xhr.getResponseHeader === \"function\" && !xhr.getResponseHeader(\"HX-Redirect\")) return; } catch (e) { return; }",
  "  const elt = detail.elt;",
  "  const form = elt && elt.closest ? elt.closest(\"form[data-task-form]\") : null;",
  "  if (!form) return;",
  "  if (form._taskDraftTimer) { clearTimeout(form._taskDraftTimer); form._taskDraftTimer = null; }",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  try { localStorage.removeItem(key); } catch (e) {}",
  "});",
  "document.addEventListener(\"submit\", function (event) {",
  "  const form = event.target;",
  "  if (!form || !form.matches || !form.matches('form[action=\"/logout\"]')) return;",
  "  try {",
  "    const remove = [];",
  "    for (let i = 0; i < localStorage.length; i += 1) {",
  "      const key = localStorage.key(i);",
  "      if (key && key.indexOf(\"siftq.task-draft:\") === 0) remove.push(key);",
  "    }",
  "    remove.forEach(function (key) { localStorage.removeItem(key); });",
  "  } catch (e) {}",
  "});",
].join("\n");
