export const TASK_LIST_SELECTION_SCRIPT = [
  "function initializeTaskListSelection() {",
  "  const list = document.querySelector(\"[data-task-list]\");",
  "  if (!list || list.dataset.selectionInitialized === \"true\") return;",
  "  list.dataset.selectionInitialized = \"true\";",
  "  const selectAll = list.querySelector(\"[data-task-select-all]\");",
  "  const statusTabs = list.querySelector(\"[data-task-status-tabs]\");",
  "  const selectionSummary = list.querySelector(\"[data-task-selection-summary]\");",
  "  const actionButtons = list.querySelectorAll(\"[data-task-action]\");",
  "  const feedback = list.querySelector(\"[data-task-selection-feedback]\");",
  "  let actionPending = false;",
  "  const selects = function () { return Array.prototype.slice.call(list.querySelectorAll(\"[data-task-select]\")); };",
  "  function selectedInputs() {",
  "    return selects().filter(function (checkbox) { return checkbox.checked; }).map(function (checkbox) {",
  "      const row = checkbox.closest(\"[data-task-row]\");",
  "      const id = row && row.getAttribute(\"data-task-id\");",
  "      const version = row && row.getAttribute(\"data-version\");",
  "      if (!id || !version) return null;",
  "      return { id: id, version: Number(version) };",
  "    }).filter(function (input) { return input !== null; });",
  "  }",
  "  function showFeedback(message) {",
  "    if (!feedback) return;",
  "    feedback.hidden = false;",
  "    feedback.classList.add(\"error\");",
  "    feedback.textContent = message;",
  "  }",
  "  function setPending(pending) {",
  "    actionPending = pending;",
  "    actionButtons.forEach(function (button) { button.disabled = pending || selectedInputs().length === 0; });",
  "    if (selectAll) selectAll.disabled = pending || selects().length === 0;",
  "  }",
  "  function syncSelection() {",
  "    const checkboxes = selects();",
  "    const selected = checkboxes.filter(function (checkbox) { return checkbox.checked; });",
  "    if (selectAll) { selectAll.checked = checkboxes.length > 0 && selected.length === checkboxes.length; selectAll.indeterminate = selected.length > 0 && selected.length < checkboxes.length; selectAll.disabled = actionPending || checkboxes.length === 0; }",
  "    if (statusTabs) statusTabs.hidden = selected.length > 0;",
  "    if (selectionSummary) { selectionSummary.hidden = selected.length === 0; selectionSummary.textContent = selected.length + \" of \" + checkboxes.length + \" selected\"; }",
  "    actionButtons.forEach(function (button) { button.disabled = actionPending || selected.length === 0; });",
  "    list.querySelectorAll(\"[data-task-row]\").forEach(function (row) {",
  "      const checkbox = row.querySelector(\"[data-task-select]\");",
  "      if (checkbox) row.classList.toggle(\"is-selected\", checkbox.checked);",
  "    });",
  "  }",
  "  if (selectAll) selectAll.addEventListener(\"change\", function () { selects().forEach(function (checkbox) { checkbox.checked = selectAll.checked; }); syncSelection(); });",
  "  list.addEventListener(\"change\", function (event) { if (event.target.matches(\"[data-task-select]\")) syncSelection(); });",
  "  function submitBulkAction(action, inputs) {",
  "    setPending(true);",
  "    const isDelete = action === \"delete\";",
  "    const request = fetch(isDelete ? \"/api/tasks/bulk\" : \"/api/tasks/bulk/status\", {",
  "      method: isDelete ? \"DELETE\" : \"PATCH\",",
  "      headers: { \"Content-Type\": \"application/json\" },",
  "      body: JSON.stringify(isDelete ? { tasks: inputs } : { status: action, tasks: inputs }),",
  "    });",
  "    request.then(function (response) {",
  "      if (!response.ok) { showFeedback(response.status === 409 ? \"Task was updated elsewhere. Reload the list.\" : \"Bulk action failed.\"); return false; }",
  "      return true;",
  "    }).then(function (succeeded) { if (succeeded) { if (isDelete && typeof removeTaskDraft === \"function\") inputs.forEach(function (input) { removeTaskDraft(input.id); }); window.location.reload(); } }).catch(function () { showFeedback(\"Bulk action failed.\"); }).finally(function () { setPending(false); });",
  "  }",
  "  function renderDeleteDialog(inputs) {",
  "    const backdrop = document.createElement(\"div\");",
  "    backdrop.className = \"matrix-modal-backdrop\";",
  "    const dialog = document.createElement(\"div\");",
  "    dialog.className = \"matrix-modal\";",
  "    const message = document.createElement(\"p\");",
  "    message.className = \"matrix-modal-text\";",
  "    message.textContent = \"選択した\" + inputs.length + \"件のタスクを削除しますか？\";",
  "    dialog.appendChild(message);",
  "    const row = document.createElement(\"div\");",
  "    row.className = \"matrix-modal-actions\";",
  "    [\"キャンセル\", \"削除\"].forEach(function (label, index) {",
  "      const button = document.createElement(\"button\");",
  "      button.type = \"button\";",
  "      button.className = \"matrix-modal-button \" + (index === 1 ? \"matrix-modal-button--danger\" : \"matrix-modal-button--cancel\");",
  "      button.textContent = label;",
  "      button.setAttribute(\"data-task-list-delete\", index === 1 ? \"confirm\" : \"cancel\");",
  "      row.appendChild(button);",
  "    });",
  "    dialog.appendChild(row);",
  "    backdrop.addEventListener(\"click\", function (event) {",
  "      const button = event.target.closest ? event.target.closest(\"[data-task-list-delete]\") : null;",
  "      if (!button) return;",
  "      backdrop.remove();",
  "      if (button.getAttribute(\"data-task-list-delete\") === \"confirm\") submitBulkAction(\"delete\", inputs);",
  "    });",
  "    backdrop.appendChild(dialog);",
  "    document.body.appendChild(backdrop);",
  "  }",
  "  list.addEventListener(\"click\", function (event) {",
  "    const action = event.target.closest ? event.target.closest(\"[data-task-action]\") : null;",
  "    if (!action) return;",
  "    const inputs = selectedInputs();",
  "    if (actionPending || inputs.length === 0) return;",
  "    event.preventDefault();",
  "    const actionName = action.getAttribute(\"data-task-action\");",
  "    const menu = action.closest(\".task-bulk-menu\");",
  "    if (menu) menu.removeAttribute(\"open\");",
  "    if (actionName === \"delete\") { renderDeleteDialog(inputs); return; }",
  "    if (actionName === \"do\" || actionName === \"done\" || actionName === \"skip\") submitBulkAction(actionName, inputs);",
  "  });",
  "  syncSelection();",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeTaskListSelection);",
  "document.addEventListener(\"htmx:load\", initializeTaskListSelection);",
].join("\n");
